### ISSUE TITLE
How to select a file in photos app

### ISSUE THREAD

**Issue by burra06** [dtmilano/AndroidViewClient#134]
1.	Able to start the photos app
2.	Used dump.py to get the current view details
3.	Used getViewById(id/id_noid/#) in the script to get the view of specific media file
4.	Used View.touch() to select the media file.
From the logs I see only the listview coordinates touched but not the media file view, what ever ID I use. Can somebody help on APIs to be used to select a specific media file in ViewClient for photos app

**Comment by burra06** [comment]
getviewbyId output-- View[ class=android.widget.FrameLayout index=1 selected=false checked=false clickable=false package=com.google.android.apps.plus text= long-clickable=false enabled=true bounds=((0, 129), (1200, 1872)) content-desc= focusable=false focused=false uniqueId=id/no_id/21 checkable=false resource-id= password=false class=android.widget.FrameLayout scrollable=false ]   parent=android.widget.RelativeLayout

dump.py output -- View[ class=android.view.View index=3 selected=false NAF=true clickable=true package=com.google.android.apps.plus text= long-clickable=true enabled=true bounds=((903, 430), (1200, 727)) content-desc= focusable=false focused=false uniqueId=id/no_id/21 checkable=false resource-id= password=false class=android.view.View checked=false scrollable=false ]   parent=android.widget.LinearLayout

**Comment by dtmilano** [comment]
Are you talking about Google *Photos*?
Which version?
Which android version?
Which device?

I'm not sure what you mean by "select a file" but I was using `culebra -G`
to generate some scripts and I could navigate through the UI and select
photos and to select and play videos with no problem.
Give `culebra -G` a try. If it fails too, provide more details to be able
to reproduce the case.


On Wed, Feb 18, 2015 at 6:52 PM, burra06 <notifications@github.com> wrote:

> getviewbyId output-- View[ class=android.widget.FrameLayout index=1
> selected=false checked=false clickable=false
> package=com.google.android.apps.plus text= long-clickable=false
> enabled=true bounds=((0, 129), (1200, 1872)) content-desc= focusable=false
> focused=false uniqueId=id/no_id/21 checkable=false resource-id=
> password=false class=android.widget.FrameLayout scrollable=false ]
> parent=android.widget.RelativeLayout
>
> dump.py output -- View[ class=android.view.View index=3 selected=false
> NAF=true clickable=true package=com.google.android.apps.plus text=
> long-clickable=true enabled=true bounds=((903, 430), (1200, 727))
> content-desc= focusable=false focused=false uniqueId=id/no_id/21
> checkable=false resource-id= password=false class=android.view.View
> checked=false scrollable=false ] parent=android.widget.LinearLayout
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/134#issuecomment-74974507>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by burra06** [comment]
Thank You Very much Milano. That helped. You saved my day.
