### ISSUE TITLE
Problem with missing version header?

### ISSUE THREAD

**Issue by sleekweasel** [dtmilano/AndroidViewClient#136]
This is probably a stupid user question, but...

I downloaded AndroidViewClient to a directory and exported the environment variable.
I tried running culebra and dump, they both work. Trying culebra -G complains about a missing Pillow, so I installed that with macports on my Yosemite mac.

Now it's giving me the following, and I can't seem to run 'python easy_install.py develop' or find 'setup.py'.

Sorry for 'help', but help?

> $ ./tools/culebra -G
> #! /usr/bin/env python
> # -*- coding: utf-8 -*-
> '''
> Copyright (C) 2013-2014  Diego Torres Milano
> Created on 2015-03-05 by Culebra v10.1.0
>                       __    __    __    __
>                      /  \  /  \  /  \  /  \ 
> ____________________/  __\/  __\/  __\/  __\_____________________________
___________________/  /__/  /__/  /__/  /________________________________
>                    | / \   / \   / \   / \   \___
>                    |/   \_/   \_/   \_/   \    o \ 
>                                            \_____/--<
> @author: Diego Torres Milano
> @author: Jennifer E. Swofford (ascii art snake)
> '''
> 
> 
> import re
> import sys
> import os
> 
> from com.dtmilano.android.viewclient import ViewClient
> 
> TAG = 'CULEBRA'
> 
> _s = 5
> _v = '--verbose' in sys.argv
> 
> 
> kwargs1 = {'ignoreversioncheck': False, 'verbose': False, 'ignoresecuredevice': False}
> device, serialno = ViewClient.connectToDeviceOrExit(**kwargs1)
> kwargs2 = {'startviewserver': True, 'forceviewserveruse': False, 'autodump': False, 'ignoreuiautomatorkilled': True}
> vc = ViewClient(device, serialno, **kwargs2)
> #vc.dump(window='-1') # FIXME: seems not needed
> 
> Traceback (most recent call last):
>   File "./tools/culebra", line 1033, in <module>
>     runCulebron()
>   File "./tools/culebra", line 759, in runCulebron
>     culebron = Culebron(vc, printOperation, options[CulebraOptions.SCALE])
>   File "/Users/timbaverstock/git/AndroidViewClient/src/com/dtmilano/android/culebron.py", line 183, in __init__
>     "share/pixmaps/culebra.png")
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1128, in resource_filename
>     return get_provider(package_or_requirement).get_resource_filename(
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 394, in get_provider
>     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 672, in find
>     if dist is not None and dist not in req:
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2915, in __contains__
>     item = item.version
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2528, in version
>     raise ValueError(tmpl % self.PKG_INFO, self)
> ValueError: ("Missing 'Version:' header and/or PKG-INFO file", androidviewclient [unknown version] (/Users/timbaverstock/git/AndroidViewClient/src))

**Comment by sleekweasel** [comment]
I was trying to execute the 'sudo easy_install --upgrade androidviewclient' command from the wrong directory for some reason.

Sitting in the AndroidViewClient directory, it ran. Now I'm getting 

>  File "tools/culebra", line 1017, in <module>
>    vc.dump(window=options[CulebraOptions.WINDOW])
>  File "/Users/timbaverstock/git/AndroidViewClient/src/com/dtmilano/android/viewclient.py", line 3044, in dump
>    raise RuntimeError('ERROR: Empty UiAutomator dump was received')
> RuntimeError: ERROR: Empty UiAutomator dump was received

which is much less embarrassing.

**Comment by dtmilano** [comment]
You can try:

$ adb shell uiautomator dump

to see if it works. The error above is telling you that the received output
was empty.
Start with a simple Activity running (i.e. Calculator).


On Fri, Mar 6, 2015 at 9:34 AM, sleekweasel <notifications@github.com>
wrote:

> I was trying to execute the 'sudo easy_install --upgrade
> androidviewclient' command from the wrong directory for some reason.
>
> Sitting in the AndroidViewClient directory, it ran. Now I'm getting
>
> File "tools/culebra", line 1017, in
> vc.dump(window=options[CulebraOptions.WINDOW])
> File
> "/Users/timbaverstock/git/AndroidViewClient/src/com/dtmilano/android/viewclient.py",
> line 3044, in dump
> raise RuntimeError('ERROR: Empty UiAutomator dump was received')
> RuntimeError: ERROR: Empty UiAutomator dump was received
>
> which is much less embarrassing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/136#issuecomment-77567711>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by sleekweasel** [comment]
Hi, thanks for getting back to me.

That adb command works happily - lots of view-related XML in an sdcard file (although sadly, not the textbox hint fields).

I tried uninstalling macports and installing everything with brew instead, and that results in a graphical display coming up that I can interact through - thanks! I don't know whether it was the reinstallation of pillow, or running the easy_install from the project clone directory.

I don't know quite what I'll do when I need what I installed with macports if brew doesn't support it. :)

**Comment by dtmilano** [comment]
`easy_install` would be the best method. It doesn't (shouldn't) matter the
directory you are in as the installation is system wide.

On Fri, Mar 6, 2015 at 12:42 PM, sleekweasel <notifications@github.com>
wrote:

> Hi, thanks for getting back to me.
>
> That adb command works happily - lots of view-related XML in an sdcard
> file (although sadly, not the textbox hint fields).
>
> I tried uninstalling macports and installing everything with brew instead,
> and that results in a graphical display coming up that I can interact
> through - thanks! I don't know whether it was the reinstallation of pillow,
> or running the easy_install from the project clone directory.
>
> I don't know quite what I'll do when I need what I installed with macports
> if brew doesn't support it. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/136#issuecomment-77601681>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by awkasem** [comment]
got the same problem and resolved it by running the setup.py file under AndroidViewClient as follow:

python setup.py develop
