### ISSUE TITLE
Id of Fragment disappeared

### ISSUE THREAD

**Issue by sedonaFR** [dtmilano/AndroidViewClient#137]
I used the version 8.15.3 before.
Since I updated to the last version (10.1.0) through easy_install, the dump() method never retrieve the ids of Fragments.

-I use the same device, same API level, the same apk, same android SDK, and the ids still appears on android Monitor
-It happens on OpenSuse and MacOS

Thanks

**Comment by dtmilano** [comment]
| -I use the same device, same API level, the same apk, same android SDK, and the ids still appears on android Monitor

Which is...?

**Comment by sedonaFR** [comment]
Which is:
Galaxy Ace 3 with android version 4.4.4
In fact I have also other ids of Layout that are not recognized anymore. I got back to 8.15.3 and it is working again. 
I'll update this issue when I'll find the exact version when the bug appears

By the way, thanks for your work, it is so great to build automatic test scenarii

**Comment by dtmilano** [comment]
The only thing that comes to my mind is the use of *compression* in UiAutomator dump.
If you update to **AndroidViewClient 10.1.5** the option is now exposed.
Simply generate a `culebra` script as usual and then edit it and set `compresseddump` to `False`:

    kwargs2 = {'compresseddump': False, 'startviewserver': True, 'forceviewserveruse': False, 'autodump': False, 'ignoreuiautomatorkilled': True}

Test your case again and I hope we have found the reason.

**Comment by sedonaFR** [comment]
Your mind is correct, thank you!
