### ISSUE TITLE
Windows OS - Culebra GUI is not showing GUI Due to Exception: PIL or Pillow is needed for GUI mode

### ISSUE THREAD

**Issue by atobulredy** [dtmilano/AndroidViewClient#143]
Hi,

I am working on windows machine.
I am not able to launch Culebra GUI tool. Its failing with an below error.
Its failed with due to Pillow is needed or PIL software. Let me know how to configure Pillow repository in my machine.

D:\Mobile recorder\AndroidViewClient-master\tools>python culebra -G
#! /usr/bin/env python
# -*- coding: utf-8 -*-
'''
Copyright (C) 2013-2014  Diego Torres Milano
Created on 2015-05-19 by Culebra v10.5.0
                      __    __    __    __
                     /  \  /  \  /  \  /  \
____________________/  __\/  __\/  __\/  __\_____________________________
___________________/  /__/  /__/  /__/  /________________________________
                   | / \   / \   / \   / \   \___
                   |/   \_/   \_/   \_/   \    o \
                                           \_____/--<
@author: Diego Torres Milano
@author: Jennifer E. Swofford (ascii art snake)
'''

import re
import sys
import os

from com.dtmilano.android.viewclient import ViewClient

TAG = 'CULEBRA'

_s = 5
_v = '--verbose' in sys.argv

kwargs1 = {'ignoreversioncheck': False, 'verbose': False, 'ignoresecuredevice':
False}
device, serialno = ViewClient.connectToDeviceOrExit(**kwargs1)
kwargs2 = {'compresseddump': True, 'startviewserver': True, 'forceviewserveruse
: False, 'autodump': False, 'ignoreuiautomatorkilled': True}
vc = ViewClient(device, serialno, **kwargs2)
#vc.dump(window='-1') # FIXME: seems not needed

Traceback (most recent call last):
  File "culebra", line 1080, in <module>
    runCulebron()
  File "culebra", line 780, in runCulebron
    Culebron.checkDependencies()
  File "D:\Mobile recorder\AndroidViewClient-master\src\com\dtmilano\android\cu
ebron.py", line 165, in checkDependencies
    ''')
Exception: PIL or Pillow is needed for GUI mode

On Ubuntu install

   $ sudo apt-get install python-imaging python-imaging-tk

On OSX install

   $ brew install homebrew/python/pillow

**Comment by atobulredy** [comment]
I just tried in Mac machine tooo with Pillow installation. Still facing same issue.

Please find the below error logs

igatemac:scripts admnistrator$ export ANDROID_VIEW_CLIENT_HOME=/Users/admnistrator/Downloads/AndroidViewClient-master
igatemac:scripts admnistrator$ cd /Users/admnistrator/Downloads/AndroidViewClient-master
igatemac:AndroidViewClient-master admnistrator$ cd tools
igatemac:tools admnistrator$ ./culebra -G
#! /usr/bin/env python
# -*- coding: utf-8 -*-
'''
Copyright (C) 2013-2014  Diego Torres Milano
Created on 2015-05-19 by Culebra v10.5.0
                      __    __    __    __
                     /  \  /  \  /  \  /  \ 
____________________/  __\/  __\/  __\/  __\_____________________________
___________________/  /__/  /__/  /__/  /________________________________
                   | / \   / \   / \   / \   \___
                   |/   \_/   \_/   \_/   \    o \ 
                                           \_____/--<
@author: Diego Torres Milano
@author: Jennifer E. Swofford (ascii art snake)
'''


import re
import sys
import os

from com.dtmilano.android.viewclient import ViewClient

TAG = 'CULEBRA'

_s = 5
_v = '--verbose' in sys.argv


kwargs1 = {'ignoreversioncheck': False, 'verbose': False, 'ignoresecuredevice': False}
device, serialno = ViewClient.connectToDeviceOrExit(**kwargs1)
kwargs2 = {'compresseddump': True, 'startviewserver': True, 'forceviewserveruse': False, 'autodump': False, 'ignoreuiautomatorkilled': True}
vc = ViewClient(device, serialno, **kwargs2)
#vc.dump(window='-1') # FIXME: seems not needed

Traceback (most recent call last):
  File "./culebra", line 1080, in <module>
    runCulebron()
  File "./culebra", line 780, in runCulebron
    Culebron.checkDependencies()
  File "/Users/admnistrator/Downloads/AndroidViewClient-master/src/com/dtmilano/android/culebron.py", line 165, in checkDependencies
    ''')
Exception: PIL or Pillow is needed for GUI mode

On Ubuntu install

   $ sudo apt-get install python-imaging python-imaging-tk

On OSX install

   $ brew install homebrew/python/pillow

igatemac:tools admnistrator$ brew install homebrew/python/pillow
Warning: pillow-2.7.0 already installed

**Comment by atobulredy** [comment]
Issue is fixed by installing pip install pillow.

**Comment by sanjatpanigrahi** [comment]
I tried the aforementioned steps but still facing the same issue. I installed the pillow using the command
pip install pillow

**Comment by riverscuomo** [comment]
I had the same problem: Pillow was installed but I was getting the "Pillow is needed for GUI mode" exception. Then I realized Pillow was installed in python 3 and not python 2. 

[Instructions for how to install a package to a specific version of python.](https://stackoverflow.com/questions/10919569/install-a-module-using-pip-for-specific-python-version)
