### ISSUE TITLE
view.setText()

### ISSUE THREAD

**Issue by gdobra** [dtmilano/AndroidViewClient#144]
View.SetText currently deletes the old text by repeatedly deleting its every character.

On a long click, all the text is selected, thus being able to delete the old text on the next key input. Faster than deleting every character.

**Comment by gdobra** [comment]
or, well... that doesn't seem to work with chinese characters. only one character is selected...

**Comment by dtmilano** [comment]
@ktkopone very good point. How can I forgot about that as IIRC I patched `input` to support multiple keycodes ;-)
