### ISSUE TITLE
Error running dump-simple.py on ubunutu ValueError: received does not contain valid XML data

### ISSUE THREAD

**Issue by rajpoojary** [dtmilano/AndroidViewClient#155]
Not sure if this is a actual bug or setup issue. Followed all the instruction from Wiki, got it working o mac but when running the same command on Ubuntu I see the following error. Any feedback will be helpful.

Command ran was: python dump-simple.py

Actual device serialno=emulator-5554
Traceback (most recent call last):
  File "dump-simple.py", line 28, in <module>
    ViewClient(*ViewClient.connectToDeviceOrExit(verbose=True)).traverse(transform=ViewClient.TRAVERSE_CIT)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.0.1-py2.7.egg/com/dtmilano/android/viewclient.py", line 2467, in __init__
    self.dump()
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.0.1-py2.7.egg/com/dtmilano/android/viewclient.py", line 3141, in dump
    self.setViewsFromUiAutomatorDump(received)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.0.1-py2.7.egg/com/dtmilano/android/viewclient.py", line 2839, in setViewsFromUiAutomatorDump
    self.__parseTreeFromUiAutomatorDump(received)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.0.1-py2.7.egg/com/dtmilano/android/viewclient.py", line 2997, in __parseTreeFromUiAutomatorDump
    raise ValueError("received does not contain valid XML data")
ValueError: received does not contain valid XML data

**Comment by dtmilano** [comment]
Is the same Android device connected on Ubuntu and Mac or is it different?
Does `dump` command work?


On Mon, Nov 30, 2015 at 6:03 PM, rajpoojary <notifications@github.com>
wrote:

> Not sure if this is a actual bug or setup issue. Followed all the
> instruction from Wiki, got it working o mac but when running the same
> command on Ubuntu I see the following error. Any feedback will be helpful.
>
> Command ran was: python dump-simple.py
>
> Actual device serialno=emulator-5554
> Traceback (most recent call last):
> File "dump-simple.py", line 28, in
>
> ViewClient(*ViewClient.connectToDeviceOrExit(verbose=True)).traverse(transform=ViewClient.TRAVERSE_CIT)
> File
> "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.0.1-py2.7.egg/com/dtmilano/android/viewclient.py",
> line 2467, in *init*
> self.dump()
> File
> "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.0.1-py2.7.egg/com/dtmilano/android/viewclient.py",
> line 3141, in dump
> self.setViewsFromUiAutomatorDump(received)
> File
> "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.0.1-py2.7.egg/com/dtmilano/android/viewclient.py",
> line 2839, in setViewsFromUiAutomatorDump
> self.__parseTreeFromUiAutomatorDump(received)
> File
> "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.0.1-py2.7.egg/com/dtmilano/android/viewclient.py",
> line 2997, in __parseTreeFromUiAutomatorDump
> raise ValueError("received does not contain valid XML data")
> ValueError: received does not contain valid XML data
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/155>.
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by rajpoojary** [comment]
Sorry, should have mentioned I am using emulator. I was able to get around this problem by creating SD card and setting it on the emulator.
It seems from the code that androidviewclient  talks to uiautomatorviewer and saved the information to sd card on device.

**Comment by dtmilano** [comment]
It depends very much of the version of some components. There are some
combinations that allow you to use a device or emulator with no storage and
being able to obtain the dump anyway.
Is your problem solved?
Let me know if you need more help.

Cheers.

On Tue, Dec 1, 2015 at 2:14 PM, rajpoojary <notifications@github.com> wrote:

> Sorry, should have mentioned I am using emulator. I was able to get around
> this problem by creating SD card and setting it on the emulator.
> It seems from the code that androidviewclient talks to uiautomatorviewer
> and saved the information to sd card on device.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/155#issuecomment-161066679>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by rajpoojary** [comment]
Yes my issues is resolved, Thanks

**Comment by dtmilano** [comment]
Just in case you want to know more, here is the code from `viewclient.py`:

```
                if api >= 23:
                    # In API 23 the process' stdout,in and err are
connected to the socket not to the pts as in
                    # previous versions, so we can't redirect to /dev/tty
                    received = self.device.shell('uiautomator dump %s
/sdcard/window_dump.xml >/dev/null && cat /sdcard/window_dump.xml' %
('--compressed' if self.compressedDump else ''))
                else:
                    # NOTICE:
                    # Using /dev/tty this works even on devices with no
sdcard
                    received = self.device.shell('uiautomator dump %s
/dev/tty >/dev/null' % ('--compressed' if api >= 18 and self.compressedDump
else ''))
```

On Tue, Dec 1, 2015 at 4:58 PM, rajpoojary <notifications@github.com> wrote:

> Yes my issues is resolved, Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/155#issuecomment-161108527>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients
