### ISSUE TITLE
global name 'bytearray' is not defined when ViewClient.connectToDeviceOrExit()) is invoked

### ISSUE THREAD

**Issue by mannnodaada** [dtmilano/AndroidViewClient#156]
Unable to attach the script or log. Hence proving the complete script and log.

Below is my script:

```
#!/usr/bin/env python

# Imports path
import os.path
import sys

sys.path.append('D:\\Manoj\\Projects\\CTS\\Android\\AndroidViewClient-master\\src')

# Imports the monkeyrunner modules used by this program
from com.android.monkeyrunner import MonkeyRunner, MonkeyDevice

from com.dtmilano.android.viewclient import ViewClient

# Connects to the current device, returning a MonkeyDevice object
device = MonkeyRunner.waitForConnection()

########################################################################
# CtsActivities function defines all the tests that needs to be executed
########################################################################
def CtsActivities():

    # Sets a variable with the package's internal name
    package = "com.android.cts.verifier"

    # Sets a variable with the name of a Main Activity in the package
    activity = "com.android.cts.verifier.CtsVerifierActivity"

    # Sets the name of the component to start
    runComponent = package + "/" + activity

    # Runs the component
    device.startActivity(component=runComponent)

    # Sleep a while
    MonkeyRunner.sleep(2);

    ########################################################################
    # CTS Sensor Batching Tests
    ########################################################################
 
    # Sets a variable with the name of CTS Sensor Batching Tests Activity in the package
    activity = "com.android.cts.verifier.sensors.SensorBatchingTestsActivity"
 
    # Sets the name of the component to start
    runComponent = package + "/" + activity
 
    # Runs the component
    device.startActivity(component=runComponent)
 
    # Sleep a while
    MonkeyRunner.sleep(2);

    vc = ViewClient(*ViewClient.connectToDeviceOrExit())
    vc.dump
    touchProject = vc.findViewByIdorRaise('id/NEXT')
    touchProject.touch()

    # Close the Verifier app on the test vehicle
    device.shell('am force-stop com.android.cts.verifier')


# Call the CtsActivity function
CtsActivities();
```

Below is the log

D:\Manoj\Projects\CTS\Android\sdk\tools>monkeyrunner verifier.py
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
] Script terminated due to an exception
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]Traceback (most recent call last):
  File "D:\Manoj\Projects\CTS\Android\sdk\tools\verifier.py", line 758, in <modu
le>
    CtsActivities();
  File "D:\Manoj\Projects\CTS\Android\sdk\tools\verifier.py", line 89, in CtsAct
ivities
    vc = ViewClient(*ViewClient.connectToDeviceOrExit())
  File "D:\Manoj\Projects\CTS\Android\AndroidViewClient-master\src\com\dtmilano\
android\viewclient.py", line 2581, in connectToDeviceOrExit
    device = adbclient.AdbClient(serialno, ignoreversioncheck=ignoreversioncheck
, timeout=timeout)
  File "D:\Manoj\Projects\CTS\Android\AndroidViewClient-master\src\com\dtmilano\
android\adb\adbclient.py", line 158, in __init__
    self.checkVersion(ignoreversioncheck)
  File "D:\Manoj\Projects\CTS\Android\AndroidViewClient-master\src\com\dtmilano\
android\adb\adbclient.py", line 299, in checkVersion
    self.__send('host:version', reconnect=False)
  File "D:\Manoj\Projects\CTS\Android\AndroidViewClient-master\src\com\dtmilano\
android\adb\adbclient.py", line 234, in _AdbClient__send
    b = bytearray(msg, 'utf-8')
NameError: global name 'bytearray' is not defined

151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.Py.NameError(Py.java:260)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFrame.getglobal(PyFrame.java:265)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.adb.adbclient$py._AdbClient__send$17(D:\Manoj\Pr
ojects\CTS\Android\AndroidViewClient-master\src\com\dtmilano\android\adb\adbclie
nt.py:242)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.adb.adbclient$py.call_function(D:\Manoj\Projects
\CTS\Android\AndroidViewClient-master\src\com\dtmilano\android\adb\adbclient.py)

151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:194)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.__call__(PyFunction.java:387)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyMethod.__call__(PyMethod.java:211)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.adb.adbclient$py.checkVersion$21(D:\Manoj\Projec
ts\CTS\Android\AndroidViewClient-master\src\com\dtmilano\android\adb\adbclient.p
y:310)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.adb.adbclient$py.call_function(D:\Manoj\Projects
\CTS\Android\AndroidViewClient-master\src\com\dtmilano\android\adb\adbclient.py)

151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:141)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.__call__(PyFunction.java:327)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyMethod.__call__(PyMethod.java:124)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.adb.adbclient$py.__init__$9(D:\Manoj\Projects\CT
S\Android\AndroidViewClient-master\src\com\dtmilano\android\adb\adbclient.py:173
)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.adb.adbclient$py.call_function(D:\Manoj\Projects
\CTS\Android\AndroidViewClient-master\src\com\dtmilano\android\adb\adbclient.py)

151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:194)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.__call__(PyFunction.java:387)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.__call__(PyFunction.java:381)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyInstance.__init__(PyInstance.java:120)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyClass.__call__(PyClass.java:194)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyObject.__call__(PyObject.java:320)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.viewclient$py.connectToDeviceOrExit$96(D:\Manoj\
Projects\CTS\Android\AndroidViewClient-master\src\com\dtmilano\android\viewclien
t.py:2608)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.viewclient$py.call_function(D:\Manoj\Projects\CT
S\Android\AndroidViewClient-master\src\com\dtmilano\android\viewclient.py)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:114)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.__call__(PyFunction.java:307)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.pycode._pyx0.CtsActivities$1(D:\Manoj\Projects\CTS\Android
\sdk\tools\verifier.py:739)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.pycode._pyx0.call_function(D:\Manoj\Projects\CTS\Android\s
dk\tools\verifier.py)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:120)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.__call__(PyFunction.java:307)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.pycode._pyx0.f$0(D:\Manoj\Projects\CTS\Android\sdk\tools\v
erifier.py:758)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.pycode._pyx0.call_function(D:\Manoj\Projects\CTS\Android\s
dk\tools\verifier.py)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyCode.call(PyCode.java:18)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.Py.runCode(Py.java:1275)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.__builtin__.execfile_flags(__builtin__.java:522)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225
)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.android.monkeyrunner.ScriptRunner.run(ScriptRunner.java:116)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.android.monkeyrunner.MonkeyRunnerStarter.run(MonkeyRunnerStarter.
java:77)
151202 18:37:58.133:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.android.monkeyrunner.MonkeyRunnerStarter.main(MonkeyRunnerStarter
.java:189)

D:\Manoj\Projects\CTS\Android\sdk\tools>

I have to call monkeyrunner and not python directly. I am using the latest androidstudio and latest androidviewclient with python version 2.7

**Comment by dtmilano** [comment]
**AndroidViewClient/culebra** is a `monkeyrunner` *replacement* so you should not mix them. **AndroidViewClient/culebra** is 100% python so you must use `python` as the interpreter.
Everything you are doing now in your script using `monkeyrunner` has a replacement, completely transparent in most of the cases.

Perhaps the easiest way to start is using `culebra` that will generate the base script or unittest which you can edit to suite your needs.

For example, if you run

    culebra --start-activity=com.android.cts.verifier/com.android.cts.verifier.CtsVerifierActivity

the auto-generated script will contain the code to connect to the device and start the Activity.
You can copy and edit these lines to start the second Activity and then add

```
    touchProject.touch()

    # Close the Verifier app on the test vehicle
    device.shell('am force-stop com.android.cts.verifier')
```
and your script will be compete.

Don't forget to run the script with `python`.

**Comment by dtmilano** [comment]
An article commenting on **AndroidViewClient/culebra vs monkeyrunner**: http://dtmilano.blogspot.ca/2015/12/androidviewclientculebra-vs-monkeyrunner.html
