### ISSUE TITLE
Running CulebraTester generated js script fails on SSL handshake

### ISSUE THREAD

**Issue by steve-the-edwards** [dtmilano/AndroidViewClient#160]
This is possibly an environment issue:  CulebraTester runs fine in Chrome 47 on OSX 10.11.2 (El Capitan), and can generate and save simple script.  However, upon saving that script and running on device using included command, I receive an SSL handshake error:

Stephen-Edwardss-MacBook-Pro-3:~ steveedwards$ sudo curl -o - -v -X POST --data-urlencode ~/Documents/dev/CulebraScripts/OpenYoutube.js https://192.168.2.13:9999/Javascript
Password:
*   Trying 192.168.2.13...
* Connected to 192.168.2.13 (192.168.2.13) port 9999 (#0)
* WARNING: using IP address, SNI is being disabled by the OS.
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake

SSL issue indicates environment problem?

**Comment by dtmilano** [comment]
I notice 2 weird things:

1. why do you need `sudo` to run curl?
2. Why https instead of http is being used for the POST request?

I don't think SSL would be needed to communicate with **Culebra Tester**
server thus I've never tried it before.

On Sat, Jan 2, 2016 at 12:59 PM, Stephen Edwards <notifications@github.com>
wrote:

> This is possibly an environment issue: CulebraTester runs fine in Chrome
> 47 on OSX 10112 (El Capitan), and can generate and save simple script
> However, upon saving that script and running on device using included
> command, I receive an SSL handshake error:
>
> Stephen-Edwardss-MacBook-Pro-3:~ steveedwards$ sudo curl -o - -v -X POST
> --data-urlencode ~/Documents/dev/CulebraScripts/OpenYoutubejs
> https://192168213:9999/Javascript
> Password:
>
>    - Trying 192168213
>    - Connected to 192168213 (192168213) port 9999 (#0)
>    - WARNING: using IP address, SNI is being disabled by the OS
>    - Server aborted the SSL handshake
>    - Closing connection 0 curl: (35) Server aborted the SSL handshake
>
> SSL issue indicates environment problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/160>.
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by steve-the-edwards** [comment]
Sudo not needed.

I can try http also.

**Comment by steve-the-edwards** [comment]
Yes.  User error:

Solution:
- use http not https
- remember @/full/path/to/script.js
