### ISSUE TITLE
Cannot stop scroll event when using Culebra web UI via CulebraTester

### ISSUE THREAD

**Issue by steve-the-edwards** [dtmilano/AndroidViewClient#161]
Steps to reproduce:

1. Open CulebraTester on device
2. Run web UI on PC
3. (start instrumentation)
4. Input Scroll event via Chrome on PC (two-finger scroll in Chrome 47)
Result: Infinite Scrolling until Web UI closed

Cannot stop scroll event.

**Comment by steve-the-edwards** [comment]
Note that 'flingToEnd()' and flingBackward()/Forward() in Culebra GUI does not have this issue.

**Comment by dtmilano** [comment]
At this point in time, **Culebra Tester** is not trying to identify the
classes or the hierarchy of the Views, then it is not translating the
scroll events to `fling*()` but to `'/UiDevice/swipe?startX=' + startX +
'&startY=' + startY + '&endX=' + endX + '&endY=' + endY + '&steps=' +
steps`. I guess the number of **wheel** events received by the UI is big
and generates a huge number of request that considering the delay
introduced by `steps` may take forever to complete.

On Sat, Jan 2, 2016 at 1:10 PM, Stephen Edwards <notifications@github.com>
wrote:

> Note that 'flingToEnd()' and flingBackward()/Forward() in Culebra GUI does
> not have this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/161#issuecomment-168413251>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by steve-the-edwards** [comment]
OK - that makes good sense.
