### ISSUE TITLE
regex not working properly in __findViewWithAttributeInTreeThatMatches()

### ISSUE THREAD

**Issue by Diob** [dtmilano/AndroidViewClient#163]
I was trying to browse through folders with an app, searching for anything that ended with extension 'jpg|png|bmp|gif'. If no view was found with text matching that regex (images = re.compile('jpg|png|bmp|gif', flags=re.IGNORECASE), I would go one folder deeper.
At some point image files with the above extensions actually were shown on screen, but the findViewWithText() method always would return None after dumping the hierarchry.

After digging into the code I found out that __findViewWithAttributeInTreeThatMatches() uses match() instead of search() in "if root and attr in root.map and regex.match(root.map[attr]):" 
Is there are reason for this?

**Comment by dtmilano** [comment]
I think that `match()` gives you more control.
You can always change your regex to match what you need.

I would use

```python
>>> images = re.compile('.*\.(jpg|png|bmp|gif)$', flags=re.IGNORECASE)
>>> print images.search("file.png")
<_sre.SRE_Match object at 0x7f3767d29558>
>>> print images.search("filepng")
None
>>> print images.search("pngfile")
None
```

instead of

```python
>>> images = re.compile('jpg|png|bmp|gif', flags=re.IGNORECASE)
>>> print images.search("file.png")
<_sre.SRE_Match object at 0x7f3767d1e440>
>>> print images.search("filepng")
<_sre.SRE_Match object at 0x7f3767d1e440>
>>> print images.search("pngfile")
<_sre.SRE_Match object at 0x7f3767d1e440>
```

**Comment by Diob** [comment]
OK, sounds fair.
