### ISSUE TITLE
Adbclient.takeSnapshot() problem?

### ISSUE THREAD

**Issue by CallMeZack** [dtmilano/AndroidViewClient#164]
Hi, I've been using androidviewclient. Recently, I found a problem in function  adbclient.takeSnapshot(). The problem is the snapshot taken by adbclient.takeSnapshot() is not the same as the screen display in some devices, while it is same when snapshot is taken by device itself. For example, if there is a yellow region in the screen, it will becomes blue or other colors taken snapshot by adbclient.takeSnapshot(). The devices are haier hl-g100(4.4.4)， coolpad 7296(4.2.2)，Huawei-G750-T01, etc.﻿
The origin/actual image.
![origin](https://cloud.githubusercontent.com/assets/12027227/12408631/36c3676a-be9d-11e5-80f4-19b7c9b78f1e.png)

The shoted pic(by adbclient.takeSnapshot())
![snapshoted](https://cloud.githubusercontent.com/assets/12027227/12408633/4206aa42-be9d-11e5-94a6-617614704128.png)

**Comment by dtmilano** [comment]
You should check the value of this expression ([adbclient.py:642](https://github.com/dtmilano/AndroidViewClient/blob/master/src/com/dtmilano/android/adb/adbclient.py#L642)):

        USE_ADB_FRAMEBUFFER_METHOD = (self.getSdkVersion() < 14 or self.getSdkVersion() >= 23)

For example, you can use a debugger or just a print statement.
If the expression is `True` you may want to experiment forcing it to `False` to see if the result improves.
Let me know the outcome.

Thank for reporting the problem.

**Comment by CallMeZack** [comment]
Ok, I'll test later. Forgot to mention, the version of my 'adbclient.py' is '5.1.1', seems to be too low.

**Comment by CallMeZack** [comment]
My problem! It seems that my version is too low. I rewrite the function takeSnapshot(), i runs ok.
