### ISSUE TITLE
Is there a way to expose Culebra GUI thought http on a browser?

### ISSUE THREAD

**Issue by danielemaddaluno** [dtmilano/AndroidViewClient#165]
I would like to know if the library have a way to run culebra on a server and then expose the gui thought http so i can access to the test generation GUI (knowing the IP of the server and the port exposed) from a browser. Thanks in advance

**Comment by dtmilano** [comment]
Hi Daniele,
I'm glad you asked this question. As you may know, `culerba` UI is based on Tkinter, which is Python's de-facto standard package. Unfortunately, some things that I'm planning to do (and even things I should have done...) are very difficult in Tkinter so I decided to take a different approach for future versions. This new direction involves HTML5 and Javascript so it can be run in a browser.
`culebra` will still be maintained but not new functionality will be added.

There's an ongoing *private alpha* on Google Play. We expect to release it soon.
Just as a preview, I'm including a screenshot of the new **Culebra Tester**.

![culebra - google chrome_067](https://cloud.githubusercontent.com/assets/982482/12523949/dd61ae38-c127-11e5-8d6f-f5917db9a1b6.png)

Stay tuned!

**Comment by danielemaddaluno** [comment]
Cool!
Let me know here when it will be public available! I'll be glad to be your first beta tester ;D.

**Comment by dtmilano** [comment]
Just an update on *Culebra Tester*. A short demo video and brief description available at [dtmilano.github.io/CulebraTester/](http://dtmilano.github.io/CulebraTester/)

![screen shot 2016-03-24 at 17 45 02](https://cloud.githubusercontent.com/assets/982482/14032355/8f169670-f1e8-11e5-9b69-bf5bbcdde54b.png)

**Comment by dtmilano** [comment]
**CulebraTester** provides a real-time point and click test recording through a web browser.
If you are interested in being part of the Private Beta please fill out [this form](http://goo.gl/forms/XJk4sLQOZq).
