### ISSUE TITLE
Marshmallow and higher

### ISSUE THREAD

**Issue by timrijckaert** [dtmilano/AndroidViewClient#175]
Hiya, 

I have made a script with the help of Culebra GUI on a rooted Galaxy S4 with Android 5.0.2.
The test passes with success. However when I try to run the same script on a Moto X running Android 6.0 the script fails prematurely.

```
testSomething (__main__.CulebraTests) ... ERROR

======================================================================
ERROR: testSomething (__main__.CulebraTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./sporza-test.py", line 58, in testSomething
    self.vc.dump(window=-1)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.4.0-py2.7.egg/com/dtmilano/android/viewclient.py", line 3158, in dump
    raise RuntimeError('''ERROR: UiAutomator output contains no valid information. UiAutomator was killed, no reason given.''' + extraInfo)
RuntimeError: ERROR: UiAutomator output contains no valid information. UiAutomator was killed, no reason given.

----------------------------------------------------------------------
Ran 1 test in 5.536s

FAILED (errors=1)
```

Also on a Nexus 6P running Android 6.0.1 the same thing happens.
Does dump not work on Android Marshmallow?

In my testfile I have declared
`'ignoreuiautomatorkilled': True`

Btw I'm running this on Ubuntu 15.10 
EDIT: 

Same issue on Mac OSX 10.11
Thanks in advance.

**Comment by dtmilano** [comment]
You should try to run

```
$ adb shell
$ uiautomator dump
```

to see if there's an indication of any error or if the output is empty.

On Sun, Feb 7, 2016 at 9:20 AM, Tim Rijckaert <notifications@github.com>
wrote:

> Hiya,
>
> I have made a script with the help of Culebra GUI on a rooted Galaxy S4
> with Android 502
> The test passes with success However when I try to run the same script on
> a Moto X running Android 60 the script fails prematurely
>
> testSomething (__main__CulebraTests)  ERROR
>
> ======================================================================
> ERROR: testSomething (__main__CulebraTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/sporza-testpy", line 58, in testSomething
>     selfvcdump(window=-1)
>   File "/usr/local/lib/python27/dist-packages/androidviewclient-1140-py27egg/com/dtmilano/android/viewclientpy", line 3158, in dump
>     raise RuntimeError('''ERROR: UiAutomator output contains no valid information UiAutomator was killed, no reason given''' + extraInfo)
> RuntimeError: ERROR: UiAutomator output contains no valid information UiAutomator was killed, no reason given
>
> ----------------------------------------------------------------------
> Ran 1 test in 5536s
>
> FAILED (errors=1)
>
> Also on a Nexus 6P running Android 601 the same thing happens
> Does dump not work on Android Marshmallow?
>
> In my testfile I have declared
> 'ignoreuiautomatorkilled': True
>
> Thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/175>.
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by timrijckaert** [comment]
The output from your commands
I also tried to run this on a Mac running OSX 10.11

```
mbp-tim:culebra admin$ adb shell
shell@angler:/ $ uiautomator dump                                              
Killed 
137|shell@angler:/ $ 
```

However when running on an emulator all seems fine.
Anything to do with the new permissions system in Android M?

**Comment by dtmilano** [comment]
Have you tried rebooting your device to start fresh.
Accessibility prevents `uiautomator` from obtaining the `dump`, that's why
I'm suggesting that.

On Mon, Feb 8, 2016 at 5:37 AM, Tim Rijckaert <notifications@github.com>
wrote:

> The output from your commands
> I also tried to run this on a Mac running OSX 10.11
>
> mbp-tim:culebra admin$ adb shell
> shell@angler:/ $ uiautomator dump
> Killed
> 137|shell@angler:/ $
>
> However when running on an emulator all seems fine.
> Anything to do with the new permissions system in Android M?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/175#issuecomment-181299455>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by timrijckaert** [comment]
Yes. 
Just tried that one more time. It does not seem to work.
I also tried this on a Nexus 5 running Android 6.

Any other possible issues?

**Comment by dtmilano** [comment]
On a Nexus 5X running Android 6.0.1:

```
Diegos-Mac:tmp diego$ adb shell
shell@bullhead:/ $ uiautomator dump
UI hierchary dumped to: /sdcard/window_dump.xml
shell@bullhead:/ $ getprop | grep version 
[ro.build.version.release]: [6.0.1]
[ro.build.version.sdk]: [23]
```

What about `uiautomatorviewer`, does it work?

**Comment by timrijckaert** [comment]
Works flawless on Nexus 6P

**Comment by dtmilano** [comment]
If `uiautomator dump` doesn't work on a specific device or version, then
it's an *android bug*.
As I mentioned before, it would affect `uiautomatorviewer` too.

However, as I can recognize the unreliability of it, the upcoming release
of **Culebra Tester** (briefly mentioned in
https://github.com/dtmilano/AndroidViewClient/issues/165 for a different
reason) is providing a completely new backend: **uiautomatorhelper**.
This new backend does not rely on the output of `uiautomator dump` to
access the needed functionality.
**Culebra Tester** is now undergoing a private alpha tests. The public beta
should be in a few weeks only.

On Mon, Feb 8, 2016 at 5:29 PM, Tim Rijckaert <notifications@github.com>
wrote:

> Works flawless on Nexus 6P
>
> Output from previous commands:
>
> tim@tim-Aspire-S7-392: $ adb shell
> shell@angler:/ $ uiautomator dump
> Killed
> 137|shell@angler:/ $ getprop | grep version
> [gsm.version.baseband]: [.2.6.1.c4-00008-M8994FAAAANAZM-1]
> [gsm.version.ril-impl]: [Qualcomm RIL 1.0]
> [hw.cabl.version]: [1.1.20130401]
> [ro.build.version.all_codenames]: [REL]
> [ro.build.version.base_os]: []
> [ro.build.version.codename]: [REL]
> [ro.build.version.incremental]: [2473553]
> [ro.build.version.preview_sdk]: [0]
> [ro.build.version.release]: [6.0.1]
> [ro.build.version.sdk]: [23]
> [ro.build.version.security_patch]: [2016-01-01]
> [ro.opengles.version]: [196609]
> [sys.settings_secure_version]: [6]
> [sys.settings_system_version]: [1]
> shell@angler:/ $
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/175#issuecomment-181595225>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by timrijckaert** [comment]
Waaw thanks!
I'll definitly let you know the outcome of that. 

In about a week time I'll have my hands on a Nexus 5X. I'll check that too. 

Thanks for all this work.
Keep it up!

**Comment by dtmilano** [comment]
Thanks for reporting this problem.
At this point it's very difficult for me to guess the reason. It may be another app using the accessibility framework that blocks `uiautomator dump` from being executed.
If it happens just after boot is something that's starting after BOOT_COMPLETED is received so you may have a clue here.

**Comment by timrijckaert** [comment]
OK, I found the problem I had the AccessibilityService [Barista](http://checkdroid.com/barista/) running on the 'faulty' devices. Disabling the service made Culebra work.

**Comment by dtmilano** [comment]
**CulebraTester** provides a real-time point and click test recording through a web browser.
If you are interested in being part of the Private Beta please fill out [this form](http://goo.gl/forms/XJk4sLQOZq).
