### ISSUE TITLE
RuntimeError: Couldn't find display info in 'wm size', 'dumpsys display' or 'dumpsys window'

### ISSUE THREAD

**Issue by iam-peekay** [dtmilano/AndroidViewClient#183]
![image](https://cloud.githubusercontent.com/assets/5421194/13229408/aababc7c-d955-11e5-881e-6fc4a2011942.png)

I sometimes get this error when I try to connect to the device. I am using API 23. I noticed that it happens any time I used an x68 based image. If I switch to x86_64 based image, then it works again. 

In your codebase, you throw the error after checking for either logical or physical display info. If  neither exists, you throw the error. https://github.com/dtmilano/AndroidViewClient/blob/master/src/com/dtmilano/android/adb/adbclient.py#L412

I was trying to figure out why this happens and it looks like it's because when you run ```dumpsys display``` or  ```wm size``` or ```wm density``` in adb shell of an x86 based image, it doesn't work. 
![image](https://cloud.githubusercontent.com/assets/5421194/13229957/31969ebc-d958-11e5-98a6-5b87d9712041.png)

The same commands in an x86_64 image do work perfectly fine without throwing an error. Just wanted to point out this bug.

**Comment by dtmilano** [comment]
Thanks for reporting the issue.
Is it an x86_64 emulator?

**Comment by iam-peekay** [comment]
@dtmilano As I mentioned, if I used an x86_64 based emulator, it doesn't error. If I use x86 based emulator, it throws the errors I described above.

**Comment by dtmilano** [comment]
Strange that WindowManager is not running.
Then, I assume

```
$ adb shell service check window
Service window: found
```

only returns `found` on x86_64 and not on x86.
Am I right?

**Comment by dtmilano** [comment]
Tried x86 emulator but couldn't reproduce your issue

```
root@generic_x86:/ # wm size
Physical size: 1080x1920
root@generic_x86:/ # wm density                                                
Physical density: 480
root@generic_x86:/ # uname -a
Linux localhost 3.4.67+ #38 PREEMPT Mon Jul 13 11:06:05 PDT 2015 i686
root@generic_x86:/ # getprop | egrep 'cpu.abi|version.sdk'                     
[ro.build.version.sdk]: [23]
[ro.product.cpu.abi]: [x86]
[ro.product.cpu.abilist]: [x86]
[ro.product.cpu.abilist32]: [x86]
[ro.product.cpu.abilist64]: []
root@generic_x86:/ # service check window                                   
Service window: found
```

**Comment by apandhi** [comment]
Have this same issue when the emulator is running for a long time. I have it set to restart the emulator whenever this occurs.

Would love to know why it occurs, though.

**Comment by dtmilano** [comment]
@Ashish, are you suggesting that emulator starts and `wm size` and `wm
density` work, but then if you leave the emulator running for a long time
they stop working?
If this happens is because the WindowManager died and if so you should see
some problems on screen emulator, does this happen?

On Wed, Feb 24, 2016 at 12:59 PM, Ashish Pandhi <notifications@github.com>
wrote:

> Have this same issue when the emulator is running for a long time. I have
> it set to restart the emulator whenever this occurs.
>
> Would love to know why it occurs, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/183#issuecomment-188383552>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients

**Comment by iam-peekay** [comment]
@dtmilano yeah, the error is strange. Sometimes I can reproduce it and other times I cannot.

I haven't yet been able to pin point what the cause of error is. I'll look more into it when I have some time as well.

**Comment by apandhi** [comment]
@dtmilano We run the emulator on a build server without a display so I cannot confirm whether or not the screen is functioning properly.

It works for the first 8-10 hours or so and then breaks. Though, this may vary depending on the build of the device.

**Comment by dtmilano** [comment]
Is it a standard emulator image or something you built?

On Thu, Feb 25, 2016 at 5:23 PM, Ashish Pandhi <notifications@github.com>
wrote:

> @dtmilano <https://github.com/dtmilano> We run the emulator on a build
> server without a display so I cannot confirm whether or not the screen is
> functioning properly.
>
> It works for the first 8-10 hours or so and then breaks. Though, this may
> vary depending on the build of the device.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dtmilano/AndroidViewClient/issues/183#issuecomment-189011195>
> .
>



-- 
Have you read my blog ?
http://dtmilano.blogspot.com
android junit tests ui linux cult thin clients
