### ISSUE TITLE
Incorrect ADB server version

### ISSUE THREAD

**Issue by akuholla** [dtmilano/AndroidViewClient#185]
Incorrect ADB server version 00040023 (expecting one of ['00040020', '0004001f'])

This is happening after I updated my Android SDK tools.  

Changed the version in the following file and it works now. 
./src/com/dtmilano/android/adb/adbclient.py

**Comment by dtmilano** [comment]
Great.
Would you like to create a *pull request* adding the new `adb` version number?

**Comment by ranjeetsinha13** [comment]
@dtmilano I am getting this issue for ADB version 00040028. Can you please add that to the list of valid adb versions?

**Comment by ttiganik** [comment]
I get this for 00040029

**Comment by dtmilano** [comment]
@ranjeetsinha13 please go ahead and create a PR
Check that everything works with the ADB version you are using.
