### ISSUE TITLE
ValueError: received does not contain valid XML data

### ISSUE THREAD

**Issue by qgb168** [dtmilano/AndroidViewClient#187]
android 4.4.2
screenshot：http://dzp-10011058.file.myqcloud.com/Screenshot_2016-04-07-23-53-41.png
## When emoji with an expression of error

Connecting to a device with serialno=.\* with a timeout of 10 secs...
Connected to device with serialno=.*
Actual device serialno=FA49KSR12211
Traceback (most recent call last):
  File "D:\Python27\Lib\site-packages\AndroidViewClient\examples\qgb_test_1.py", line 18, in <module>
    vc= ViewClient(device, serialno)
  File "D:\Python27\lib\site-packages\androidviewclient-11.5.3-py2.7.egg\com\dtmilano\android\viewclient.py", line 2555, in **init**
    self.dump()
  File "D:\Python27\lib\site-packages\androidviewclient-11.5.3-py2.7.egg\com\dtmilano\android\viewclient.py", line 3267, in dump
    self.setViewsFromUiAutomatorDump(received)
  File "D:\Python27\lib\site-packages\androidviewclient-11.5.3-py2.7.egg\com\dtmilano\android\viewclient.py", line 2927, in setViewsFromUiAutomatorDump
    self.__parseTreeFromUiAutomatorDump(received)
  File "D:\Python27\lib\site-packages\androidviewclient-11.5.3-py2.7.egg\com\dtmilano\android\viewclient.py", line 3108, in __parseTreeFromUiAutomatorDump
    raise ValueError("received does not contain valid XML data")
**ValueError: received does not contain valid XML data**
[Finished in 4.8s with exit code 1]
[shell_cmd: python -u "D:\Python27\Lib\site-packages\AndroidViewClient\examples\qgb_test_1.py"]
[dir: D:\Python27\Lib\site-packages\AndroidViewClient\examples]
[path: C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;D:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;D:\Program Files\Microsoft SQL Server\100\Tools\Binn\;D:\Program Files\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;D:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Roaming\npm;D:\Python27;D:\Python27\Scripts;F:\Android\jdk1.8.0_77\bin;F:\Android\jdk1.8.0_77\jre\bin;F:\Android\android-sdk\tools]

**Comment by dtmilano** [comment]
**AndroidViewClient** is relying on the information provided by `uiautomator` to obtain the tree of Views. If for some reason it fails you receive an error like the one you described.

To check if `uiautomator` is providing the information try

```
adb shell
uiautomator dump
```

and verify the content of the generated file to see if it contains valid XML or an error message.

**Comment by micren** [comment]
perhaps there view is not loaded completely when call dump()

`    def dump(self, window=-1, sleep=1):
        def _try_run(window=-1, sleep=1):
            try:
                status = True
                self._try_dump(window=window, sleep=sleep)
            except Exception, _:
                status = False
            finally:
                return status

        while 1:
            if _try_run(window=window, sleep=sleep):
                break
            time.sleep(1)

        return self.views

    def _try_dump(self, window=-1, sleep=1):
            # the original dump()`

**Comment by dtmilano** [comment]
[CulebraTester2-public](https://github.com/dtmilano/CulebraTester2-public) is more reliable under those conditions.
