### ISSUE TITLE
Accessing android java classes

### ISSUE THREAD

**Issue by corporatepiyush** [dtmilano/AndroidViewClient#191]
I am dealing with scenario where my android app is communicating external hardware device through USB.

For running acceptance test cases,  we have mocked the external device api with some internal mock implementation.

I like to call the methods of that mock class in order to simulate the input coming from device.

How i can do that with this library ?

**Comment by dtmilano** [comment]
The scripts you create are not running on the device so you should expose the API as a service you can reach from the computer the test scripts are running.
