### ISSUE TITLE
Encoding issue in dump.py

### ISSUE THREAD

**Issue by r011e** [dtmilano/AndroidViewClient#192]
I tried to get only the tags of the views with "dump -g" and got following error:

> Exception in view=View[ class=android.widget.FrameLayout id= ]   parent=None: TypeError:coercing to Unicode: need string or buffer, NoneType found
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.5.8-py2.7.egg/com/dtmilano/android/viewclient.py", line 2731, in traverseShowClassIdAndText
>     _str += eis
> TypeError: coercing to Unicode: need string or buffer, NoneType found

I tested multiple apps and it was always the same.

`dump -a` works and shows all the tags.

The android language is set to German, if that is of any help.
I didn't find a solution until now. Maybe you have any idea?

**Comment by dtmilano** [comment]
Try **11.5.9** it should fix your problem.

**Comment by r011e** [comment]
Thanks for the quick response.

I updated it and there's no error anymore.

I just wonder where difference between `dump -a`  and `dump -g` is.
It appears to be the same ouput and the information about the tags is missing.
