### ISSUE TITLE
AttributeError: type on Android emulator API17 

### ISSUE THREAD

**Issue by IKVillanes** [dtmilano/AndroidViewClient#193]
Using and android emulator API17 there is a issue with the property type() on an text element 
I'm using forceviewserver=true
I have this code:

```
 vc.dump(window=-1)
 id_nomedisciplina = vc.findViewById("id/etNomeDisciplina")
 print id_nomedisciplina
 id_nomedisciplina.touch()
 id_nomedisciplina.type("Software Test")
```

and the issue is:

```
Traceback (most recent call last):
  File "teste_agenda.py", line 83, in <module>
    Test1_17()
  File "teste_agenda.py", line 66, in Test1_17
    id_nomedisciplina.type("Software Test")
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-11.5.3-py2.7.egg/com/dtmilano/android/viewclient.py", line 414, in __getattr__
    raise AttributeError, name
AttributeError: type
```

With an android emulator API18 and the forceviewserver=false  it's working fine.
How can I resolve this?
I ask it on [here ](http://stackoverflow.com/questions/37862847/androidviewclient-on-android-emulator-api17-gives-attributeerror-type)too.
Thanks

**Comment by dtmilano** [comment]
What's the output of the line

    print id_nomedisciplina

**Comment by IKVillanes** [comment]
In API17 is:

`View[ class=android.support.v7.widget.v accessibility:getContentDescription()=null layout:getWidth()=660 isFocusableInTouchMode()=true layout:mTop=68 layout:getBaseline()=52 padding:mPaddingRight=8 measurement:mMinWidth=0 accessibility:getLabelFor()=-1 padding:mPaddingLeft=8 padding:mPaddingTop=20 padding:mUserPaddingEnd=-2147483648 focus:isFocusable()=true text:getSelectionEnd()=0 uniqueId=id/etNomeDisciplina focus:isFocused()=false isSoundEffectsEnabled()=true focus:hasFocus()=false layout:layout_width=MATCH_PARENT isHapticFeedbackEnabled()=true isInTouchMode()=true layout:layout_leftMargin=0 drawing:getScaleY()=1.0 accessibility:getImportantForAccessibility()=yes padding:mUserPaddingBottom=22 measurement:mMinHeight=0 drawing:getX()=30.0 layout:layout_endMargin=-2147483648 getFilterTouchesWhenObscured()=false drawing:getRotationY()=0.0 drawing:getTranslationY()=0.0 layout:layout_weight=0.0 layout:hasTransientState()=false layout:layout_topMargin=0 measurement:mMeasuredWidth=660 text:getRawTextDirection()=INHERIT drawing:getScaleX()=1.0 layout:layout_rightMargin=0 layout:mRight=690 isSelected()=false getScrollBarStyle()=INSIDE_OVERLAY text:getTextSize()=30.0 padding:mUserPaddingLeft=8 scrolling:mScrollY=0 scrolling:mScrollX=0 layout:layout_startMargin=-2147483648 layout:getHeight()=83 isActivated()=false mSystemUiVisibility_SYSTEM_UI_FLAG_VISIBLE=0x0 text:getSelectionStart()=0 drawing:getRotationX()=0.0 drawing:willNotCacheDrawing()=false mID=id/etNomeDisciplina drawing:getPivotY()=0.0 padding:mUserPaddingRight=8 text:getRawTextAlignment()=GRAVITY padding:mPaddingBottom=22 isHovered()=false layout:layout_bottomMargin=0 isClickable()=true drawing:willNotDraw()=false getEllipsize()=null isEnabled()=true layout:mBottom=151 mSystemUiVisibility=0 layout:getLayoutDirection()=RESOLVED_DIRECTION_LTR drawing:isOpaque()=false mViewFlags=405028865 layout:mLeft=30 layout:getRawLayoutDirection()=INHERIT getTag()=null layout:layout_height=WRAP_CONTENT layout:isLayoutRtl()=false layout:layout_gravity=NONE drawing:getSolidColor()=0 drawing:mLayerType=NONE mPrivateFlags_DRAWN=0x20 text:getTextAlignment()=GRAVITY drawing:getPivotX()=0.0 drawing:getTranslationX()=0.0 drawing:isDrawingCacheEnabled()=false drawing:getY()=68.0 measurement:mMeasuredHeight=83 oid=410bcad8 getVisibility()=VISIBLE class=android.support.v7.widget.v padding:mUserPaddingStart=-2147483648 drawing:getAlpha()=1.0 drawing:getRotation()=0.0 mPrivateFlags=16812080 text:mText= ]   parent=android.widget.LinearLayout`


and in API18 is:
`View[ class=android.widget.EditText index=2 selected=false checked=false clickable=true package=com.clawdyvan.agendadigitalaluno text=Optional long-clickable=true enabled=true bounds=((45, 540), (1035, 664)) content-desc= focusable=true focused=false uniqueId=id/no_id/6 checkable=false resource-id=com.clawdyvan.agendadigitalaluno:id/etNomeDisciplina password=false class=android.widget.EditText scrollable=false ]   parent=android.widget.ScrollView`

**Comment by dtmilano** [comment]
Yes, for some reason for API 17 the class is `class=android.support.v7.widget.v` not `EditText` and that's why `View.type()` fails.

Are you sure is the same View?
Can you add some text to the EditText before dumping the content to verify that `text:mText` in API 17 contains the same as `text=Optional` in API 18?
Or **Optional** is already there when you run on API 17 but not present in the dump?

**Comment by dtmilano** [comment]
I tried **Contacts** application on an emulator with **API 17**, creating a Contact and entering **Hello World** as Name and forcing ViewServer

    $ dump -Fa

and I got

```
View[ class=android.widget.EditText accessibility:getContentDescription()=null layout:getWidth()=528 isFocusableInTouchMode()=true layout:mTop=0 layout:getBaseline()=53 padding:mPaddingRight=24 measurement:mMinWidth=0 accessibility:getLabelFor()=-1 padding:mPaddingLeft=24 padding:mPaddingTop=14 padding:mUserPaddingEnd=-2147483648 focus:isFocusable()=true text:getSelectionEnd()=11 uniqueId=id/0x3 focus:isFocused()=true isSoundEffectsEnabled()=true focus:hasFocus()=true layout:layout_width=MATCH_PARENT isHapticFeedbackEnabled()=true isInTouchMode()=false layout:layout_leftMargin=0 drawing:getScaleY()=1.0 accessibility:getImportantForAccessibility()=yes padding:mUserPaddingBottom=16 measurement:mMinHeight=0 drawing:getX()=0.0 layout:layout_endMargin=-2147483648 getFilterTouchesWhenObscured()=false drawing:getRotationY()=0.0 drawing:getTranslationY()=0.0 layout:layout_weight=0.0 layout:hasTransientState()=false layout:layout_topMargin=0 measurement:mMeasuredWidth=528 text:getRawTextDirection()=INHERIT drawing:getScaleX()=1.0 layout:layout_rightMargin=0 layout:mRight=528 isSelected()=false getScrollBarStyle()=INSIDE_OVERLAY text:getTextSize()=36.0 padding:mUserPaddingLeft=24 scrolling:mScrollY=0 scrolling:mScrollX=0 layout:layout_startMargin=-2147483648 layout:getHeight()=96 isActivated()=false mSystemUiVisibility_SYSTEM_UI_FLAG_VISIBLE=0x0 text:getSelectionStart()=11 drawing:getRotationX()=0.0 drawing:willNotCacheDrawing()=false mID=id/0x3 drawing:getPivotY()=0.0 padding:mUserPaddingRight=24 text:getRawTextAlignment()=GRAVITY padding:mPaddingBottom=16 isHovered()=false layout:layout_bottomMargin=0 isClickable()=true drawing:willNotDraw()=false getEllipsize()=null isEnabled()=true layout:mBottom=96 mSystemUiVisibility=0 layout:getLayoutDirection()=RESOLVED_DIRECTION_LTR drawing:isOpaque()=false mViewFlags=405028865 layout:mLeft=0 layout:getRawLayoutDirection()=INHERIT getTag()=null layout:layout_height=96 layout:isLayoutRtl()=false layout:layout_gravity=NONE drawing:getSolidColor()=0 drawing:mLayerType=NONE mPrivateFlags_DRAWN=0x20 text:getTextAlignment()=GRAVITY drawing:getPivotX()=0.0 drawing:getTranslationX()=0.0 drawing:isDrawingCacheEnabled()=false drawing:getY()=0.0 measurement:mMeasuredHeight=96 oid=b324ec70 getVisibility()=VISIBLE class=android.widget.EditText padding:mUserPaddingStart=-2147483648 drawing:getAlpha()=1.0 drawing:getRotation()=0.0 mPrivateFlags=16812082 text:mText=Hello World ]   parent=android.widget.LinearLayout
```

Which is the expected result.

**Comment by IKVillanes** [comment]
Yes is the same view, I made an screenshot on [stackoverflow-question](http://stackoverflow.com/questions/37862847/androidviewclient-on-android-emulator-api17-gives-attributeerror-type)
I write the word is "Testing" and make dump. here are the results.

API17:
`View[ class=android.support.v7.widget.v accessibility:getContentDescription()=null layout:getWidth()=434 isFocusableInTouchMode()=true layout:mTop=52 layout:getBaseline()=40 padding:mPaddingRight=6 measurement:mMinWidth=0 accessibility:getLabelFor()=-1 padding:mPaddingLeft=6 padding:mPaddingTop=15 padding:mUserPaddingEnd=-2147483648 focus:isFocusable()=true text:getSelectionEnd()=7 uniqueId=id/etNomeDisciplina focus:isFocused()=true isSoundEffectsEnabled()=true focus:hasFocus()=true layout:layout_width=MATCH_PARENT isHapticFeedbackEnabled()=true isInTouchMode()=false layout:layout_leftMargin=0 drawing:getScaleY()=1.0 accessibility:getImportantForAccessibility()=yes padding:mUserPaddingBottom=16 measurement:mMinHeight=0 drawing:getX()=23.0 layout:layout_endMargin=-2147483648 getFilterTouchesWhenObscured()=false drawing:getRotationY()=0.0 drawing:getTranslationY()=0.0 layout:layout_weight=0.0 layout:hasTransientState()=false layout:layout_topMargin=0 measurement:mMeasuredWidth=434 text:getRawTextDirection()=INHERIT drawing:getScaleX()=1.0 layout:layout_rightMargin=0 layout:mRight=457 isSelected()=false getScrollBarStyle()=INSIDE_OVERLAY text:getTextSize()=23.0 padding:mUserPaddingLeft=6 scrolling:mScrollY=0 scrolling:mScrollX=0 layout:layout_startMargin=-2147483648 layout:getHeight()=63 isActivated()=false mSystemUiVisibility_SYSTEM_UI_FLAG_VISIBLE=0x0 text:getSelectionStart()=7 drawing:getRotationX()=0.0 drawing:willNotCacheDrawing()=false mID=id/etNomeDisciplina drawing:getPivotY()=0.0 padding:mUserPaddingRight=6 text:getRawTextAlignment()=GRAVITY padding:mPaddingBottom=16 isHovered()=false layout:layout_bottomMargin=0 isClickable()=true drawing:willNotDraw()=false getEllipsize()=null isEnabled()=true layout:mBottom=115 mSystemUiVisibility=0 layout:getLayoutDirection()=RESOLVED_DIRECTION_LTR drawing:isOpaque()=false mViewFlags=405028865 layout:mLeft=23 layout:getRawLayoutDirection()=INHERIT getTag()=null layout:layout_height=WRAP_CONTENT layout:isLayoutRtl()=false layout:layout_gravity=NONE drawing:getSolidColor()=0 drawing:mLayerType=NONE mPrivateFlags_DRAWN=0x20 text:getTextAlignment()=GRAVITY drawing:getPivotX()=0.0 drawing:getTranslationX()=0.0 drawing:isDrawingCacheEnabled()=false drawing:getY()=52.0 measurement:mMeasuredHeight=63 oid=4103b850 getVisibility()=VISIBLE class=android.support.v7.widget.v padding:mUserPaddingStart=-2147483648 drawing:getAlpha()=1.0 drawing:getRotation()=0.0 mPrivateFlags=16812082 text:mText=Testing ]   parent=android.widget.LinearLayout`

API18:
`View[ class=android.widget.EditText index=2 selected=false checked=false clickable=true package=com.clawdyvan.agendadigitalaluno text=Testing long-clickable=true enabled=true bounds=((45, 540), (1035, 664)) content-desc= focusable=true focused=true uniqueId=id/no_id/6 checkable=false resource-id=com.clawdyvan.agendadigitalaluno:id/etNomeDisciplina password=false class=android.widget.EditText scrollable=false ]   parent=android.widget.ScrollView`

API17:  text:mText=Testing
API18: text=Testing

**Comment by dtmilano** [comment]
Note in my previous comment that the class is **EditText** but for some reason is **android.support.v7.widget.v** in your case.

**Comment by IKVillanes** [comment]
I will test with another App. I Think it is with this specific App.

**Comment by dtmilano** [comment]
**Contacts** is a good candidate as a test App as it's available on the emulator.
