### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by vikigenius** [dtmilano/AndroidViewClient#200]
Is there any plan on providing python3 support in the near future?

**Comment by Frostie2** [comment]
Yes please! Everything is running under python3 today!

**Comment by juliomfreitas** [comment]
hi @bojanpotocnik do you consider to send a PR to this project?

Thanks for your support

**Comment by juliomfreitas** [comment]
https://github.com/dtmilano/AndroidViewClient/pull/260

hey guys, I make a PR were the py3 support is almost complete. The @bojanpotocnik was a little outdated, so I decided to make the support from the master of this repo

Att,

**Comment by kajala** [comment]
Is there any plans to release the Python 3 version?  2.7 will receive bugfix support until January 1, 2020. After the last release, 2.7 will receive no support.

**Comment by dtmilano** [comment]
The latest prerelease **v20.0.0b3** supports both python 2.7 and python 3.x.
