### ISSUE TITLE
No connected devices

### ISSUE THREAD

**Issue by IgorGanapolsky** [dtmilano/AndroidViewClient#202]
Hello,
when I try to run your samples, I always get this error:
> File "/Library/Python/2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 328, in __setTransport
    raise RuntimeError("ERROR: There are no connected devices")

Please advise,
Igor

**Comment by danafergan** [comment]
Hi Igor,

Can you type "adb devices" and see if there's any output? You might also need to type "adb start-server" to get adb running, although AndroidViewClient should start it for you...

**Comment by IgorGanapolsky** [comment]
@danafergan You are correct, my devices weren't being reported by ADB.  Fixed.
