### ISSUE TITLE
Unable to dump

### ISSUE THREAD

**Issue by IgorGanapolsky** [dtmilano/AndroidViewClient#203]
Hello,
as I understand it, I should be able to supply a device identifier as a parameter to **dump** command.  Like this:
`dump b6044c7b`

However, I get this error:
> File "/usr/local/bin/dump", line 202, in <module>
    vc.dump(window=options[WINDOW])
  File "/Library/Python/2.7/site-packages/com/dtmilano/android/viewclient.py", line 3277, in dump
    self.setViewsFromUiAutomatorDump(received)
  File "/Library/Python/2.7/site-packages/com/dtmilano/android/viewclient.py", line 2934, in setViewsFromUiAutomatorDump
    self.__parseTreeFromUiAutomatorDump(received)
  File "/Library/Python/2.7/site-packages/com/dtmilano/android/viewclient.py", line 3116, in __parseTreeFromUiAutomatorDump
    raise ValueError("received does not contain valid XML: " + receivedXml)
ValueError: received does not contain valid XML: Killed 

Did I do something wrong?

Thanks,
Igor

**Comment by dtmilano** [comment]
`dump` is relying on the information provided by `uiautomator`.
Try

   $ adb shell
   $ uiautomator dump

and check the output is generated.

**Comment by IgorGanapolsky** [comment]
Ah.  Seems to work when I only have one device attached.  I think the problem was when having multiple devices connected through USB.

**Comment by dtmilano** [comment]
Multiple devices connected at the same time are supported. That's the reason why you can specify the serial number (or regular expression) in the command line.

`usage: dump [OPTION]... [serialno]`
