### ISSUE TITLE
Unable to install through Google Play

### ISSUE THREAD

**Issue by IgorGanapolsky** [dtmilano/AndroidViewClient#204]
Hello,
I am trying to install this tool through the Beta invite I received in the email.  The instrumentation package is not installable.  Please see screenshots:
![culebra1](https://cloud.githubusercontent.com/assets/201209/19154112/2dde0060-8ba7-11e6-9351-2f53be82ce47.png)
![culebra2](https://cloud.githubusercontent.com/assets/201209/19154111/2dd8cbfe-8ba7-11e6-9282-eba51e78f725.png)

**Comment by dtmilano** [comment]
Hi @IgorGanapolsky,
If you find any *Culebra Tester* issue please use https://github.com/dtmilano/CulebraTester-public/issues.
Thanks

**Comment by IgorGanapolsky** [comment]
So I shouldn't have posted this issue?
https://github.com/dtmilano/AndroidViewClient/issues/205
