### ISSUE TITLE
Instrumentation error

### ISSUE THREAD

**Issue by IgorGanapolsky** [dtmilano/AndroidViewClient#205]
Hello,
I am running your GUI tool to generate a Python script.  However, upon running this script, I get the following error:

> # 
> ## ERROR: testSomething (**main**.CulebraTests)
> 
> Traceback (most recent call last):
>   File "test.py", line 44, in setUp
>     super(CulebraTests, self).setUp()
>   File "/Library/Python/2.7/site-packages/com/dtmilano/android/viewclient.py", line 4446, in setUp
>     self.vc = ViewClient(self.device, self.serialno, **self.kwargs2)
>   File "/Library/Python/2.7/site-packages/com/dtmilano/android/viewclient.py", line 2535, in **init**
>     self.uiAutomatorHelper = UiAutomatorHelper(device)
>   File "/Library/Python/2.7/site-packages/com/dtmilano/android/uiautomator/uiautomatorhelper.py", line 109, in **init**
>     raise RuntimeError('The target device does not contain the instrumentation for %s' % self.PACKAGE)
> ## RuntimeError: The target device does not contain the instrumentation for com.dtmilano.android.culebratester
> 
> Ran 1 test in 1.830s
> FAILED (errors=1)

Any idea what is causing this?

Thank you,
Igor

**Comment by dtmilano** [comment]
This issue could have been posted to *CulebraTester* [issues](https://github.com/dtmilano/CulebraTester-public/issues) too. However, as *CulebraTester* generates python scripts compatible with *AndroidViewClient* the distinction here is a little trickier.
