### ISSUE TITLE
After updating AndroidViewClient, cannot find device when called from ruby script

### ISSUE THREAD

**Issue by jsbakker** [dtmilano/AndroidViewClient#207]
This was working before, but I updated AndroidViewClient because the old version didn't support my updated version of ADB (25.2.2):

_Background_
Normally I automate my app using Calabash since it's portable to iOS and uses the Gherkin syntax. However, since Calabash can only control one app, I use AndroidViewClient to automate parts where my app starts an Intent for another app's Activity. I wrote the Calabash binding in ruby so it just calls my .py scripts which use AndroidViewClient and it works seamlessly.

My python script which calls into AndroidViewClient looks like this:

```
import sys
import os

sys.path.append(os.environ['ANDROID_VIEW_CLIENT_HOME'])

from com.dtmilano.android.viewclient import ViewClient

choose_text = sys.argv[1]
del sys.argv[-1]

vc = ViewClient(*ViewClient.connectToDeviceOrExit())
file_view = vc.findViewWithTextOrRaise(choose_text)
file_view.touch()
```

When I call the python script from the command line, it works fine:

`python ./features/external_support/choose_text.py "Briefcase"`

I call it from ruby like this:

```
working_dir = Dir.pwd
ret = system "python #{working_dir}/features/external_support/choose_text.py '#{choose_file}'"
unless ret
    fail("Error in talking to external app.")
end
```

Which actually used to work, but after I updated AndroidViewClient, I will consistently get this message:

```
File "./features/external_support/choose_text.py", line 14, in <module>
    vc = ViewClient(*ViewClient.connectToDeviceOrExit())
  File "C:\Python27\lib\site-packages\androidviewclient-11.5.3-py2.7.egg\com\dtmilano\android\viewclient.py", line 2669, in connectToDeviceOrExit
    device = adbclient.AdbClient(serialno, ignoreversioncheck=ignoreversioncheck, timeout=timeout)
  File "C:\Python27\lib\site-packages\androidviewclient-11.5.3-py2.7.egg\com\dtmilano\android\adb\adbclient.py", line 172, in __init__
    self.__setTransport()
  File "C:\Python27\lib\site-packages\androidviewclient-11.5.3-py2.7.egg\com\dtmilano\android\adb\adbclient.py", line 334, in __setTransport
    raise RuntimeError("ERROR: couldn't find device that matches '%s' in %s" % (self.serialno, devices))
RuntimeError: ERROR: couldn't find device that matches ''Add' in [<com.dtmilano.android.adb.adbclient.Device instance at 0x0000000003C11208>]
```

Given this happened after an update, are there any recent changes by how AndroidViewClient talks to the adb device? One guess might be that it cannot connect to the device if Calabash is currently connected (although it was able to before, but this would explain why calling the script by command line still works). Another guess might be environment variables inside the Ruby environment vs the command line's environment variables.

**Comment by dtmilano** [comment]
What was the AndroidViewClient version number that you know for sure it was working?

**Comment by dtmilano** [comment]
Do you know the serial number of the device?

Then you can try (replacing `0123456789` by your device's serial number):

`python ./features/external_support/choose_text.py "Briefcase" 0123456789`

**Comment by jsbakker** [comment]
Thanks for the quick response. I think the version that was working for me was 11.5.3, but I can't confirm because the pip uninstall nuked the egg files so I don't see them in the Recycle bin.

In the python script I changed my ViewClient constructor from this:

`vc = ViewClient(*ViewClient.connectToDeviceOrExit())`

to this:

```
kwargs = {}
device, serialno = ViewClient.connectToDeviceOrExit(serialno='myserial', **kwargs)
vc = ViewClient(device, serialno, **kwargs)
```

And it is working again. While I'm happy for this, it is still not ideal because the dev machine and the build server machine will have different devices, and possibly multiple virtual machines. I still don't have to hard-code it because I can parse `adb devices`, but if possible the old way was simpler.

**Comment by dtmilano** [comment]
The line

`RuntimeError: ERROR: couldn't find device that matches ''Add' in [<com.dtmilano.android.adb.adbclient.Device instance at 0x0000000003C11208>]`

gives another clue.
I think you are invoking the python script with more than 1 argument, then you remove the last one and **AndroidViewClient** tries to match the argument left (`Add` in the example you posted) with the serial number of the connected devices and they don't match.

Try adding

`print sys.argv`

before and after you remove elements from `sys.argv` to see what's happening.

**Comment by jsbakker** [comment]
It will just print `'c:/Src/XamarinEngage/features/external_support/see_text.py', 'Briefcase'`. I found a while back that AndroidViewClient always failed if I passed in an argument to python for my own purposes unless I delete the argument from the vector.

I changed my .py script to take a device serial number and pass it to the ViewClient, and I got things working again. I just leave it up to ruby to parse `adb devices` to get the connected device and pass into the python script.

```
test_serial = sys.argv[1]
choose_text = sys.argv[2]
del sys.argv[-1]
del sys.argv[-1]

kwargs = {}
device, serialno = ViewClient.connectToDeviceOrExit(serialno=test_serial, **kwargs)
vc = ViewClient(device, serialno, **kwargs)
```

**Comment by dtmilano** [comment]
This is how `connectToDeviceOrExit() processes command line arguments when you don't specify the serial number of the device

```
        if serialno is None:
            # eat all the extra options the invoking script may have added
            args = sys.argv
            while len(args) > 1 and args[1][0] == '-':
                args.pop(1)
            serialno = args[1] if len(args) > 1 else \
                    os.environ['ANDROID_SERIAL'] if os.environ.has_key('ANDROID_SERIAL') \
                    else '.*'
```

as you can see, extra arguments added by the caller (those starting with `-`) are removed.
But if you get the serial number by other means (ruby) it is fine if you specify the value obtained in the method parameters.

**Comment by theAddict** [comment]
@jsbakker, have you taken a look at the `ANDROID_SERIAL` environment variable? The code you've posted indicates that `serialno` is initially set to `None` for the code block above that @dtmilano points out. This if statement will set `serialno` to one of the following possibilities:

1. The first argument that doesn't start with `-`
2. The value of `ANDROID_SERIAL`
3. The regex `.*`, which should match any device.

The fact that `sys.argv` does not contain `'Add` would seem to indicate that there are no issues with the command line arguments. The fact that `'Add` was mentioned in the error message means that `serialno` wasn't set to `.*`. This leads me to believe that it's most likely your environment. If that's not the case, there's something really weird going on here.

**Comment by jsbakker** [comment]
Thanks for the explanation, guys.

I think the ''Add' came from a different run of the tests, where I was searching for the Add button, while in my example I was searching for Briefcase. My bad for mixing Briefcase into my code sample, while the error message was from an earlier test targeting Add. That still wouldn't explain why Add is still there after deleting it from argv after assigning choose_text.

My guess is that maybe Add also gets set as a Ruby environment variable, as it came from a regex in my Gherkin binding. It's possible there are other env vars while Calabash is operating. I would have to print my env vars from inside the binding on the Ruby side.

**Comment by theAddict** [comment]
@jsbakker, that makes a lot more sense! I'm assuming that with the single quote there the Add button contains more than just the word add. If this is the case then it's important to note that a single quote is not sufficient when including a space in a single argument. This would mean that ``Add` is in `sys.argv[1]`. Since it doesn't begin with a `-`, `serialno` is set to `'Add`. I've provided some examples below.

### Single Quote
```
python -i test.py 'Add Button'
>>> import sys
>>> sys.argv
['test.py', "'Add", "Button'"]
>>> del sys.argv[-1]
>>> sys.argv
['test.py', "'Add"]
```

### Double Quote
```
python -i test.py "Add Button"
>>> import sys
>>> sys.argv
['test.py', 'Add Button']
>>> del sys.argv[-1]
>>> sys.argv
['test.py']
```

**Comment by dtmilano** [comment]
Also notice that if you create a test case instead of a script (i.e. using `culebra -U`) the test runner will take care of the serial numbers in the command line with `-s` or `--serialno` options.
May not help in this specific case but worth knowing it.

```
culebra-test.py --help
Usage: culebra-test.py [options] [test] [...]

Options:
  -h, --help       Show this message
  -v, --verbose    Verbose output
  -q, --quiet      Minimal output
  -s, --serialno s The serial number[s] to connect to or 'all'
  -f, --failfast   Stop on first failure
  -c, --catch      Catch control-C and display results
  -b, --buffer     Buffer stdout and stderr during test runs

Examples:
  culebra-test.py                               - run default set of tests
  culebra-test.py MyTestSuite                   - run suite 'MyTestSuite'
  culebra-test.py MyTestCase.testSomething      - run MyTestCase.testSomething
  culebra-test.py MyTestCase                    - run all 'test*' test methods
                                               in MyTestCase
```

**Comment by jetale** [comment]
> Before deleting it will print:
> `['c:/Src/XamarinEngage/features/external_support/choose_text.py', 'Briefcase']`
> 
> After deleting:
> `['c:/Src/XamarinEngage/features/external_support/choose_text.py']`
> 
> I found a while back that AndroidViewClient always failed if I passed in an argument to python for my own purposes unless I delete the argument from the vector.
> 
> I changed my .py script to take a device serial number and pass it to the ViewClient, and I got things working again. I just leave it up to ruby to parse `adb devices` to get the connected device and pass into the python script.
> 
> ```
> test_serial = sys.argv[1]
> choose_text = sys.argv[2]
> del sys.argv[-1]
> del sys.argv[-1]
> 
> kwargs = {}
> device, serialno = ViewClient.connectToDeviceOrExit(serialno=test_serial, **kwargs)
> vc = ViewClient(device, serialno, **kwargs)
> ```

This solution by @jsbakker worked for me. Thanks @jsbakker
