### ISSUE TITLE
Request failed 404

### ISSUE THREAD

**Issue by IgorGanapolsky** [dtmilano/AndroidViewClient#210]
Hello,
I am getting these errors when trying to connect Culebra in the browser.  See screenshot:
>  Request failed.  Not found (404)
![screen shot 2016-10-28 at 9 39 30 am](https://cloud.githubusercontent.com/assets/201209/19808391/a2b26bea-9cf2-11e6-8a5b-f022c40c6825.png)

My device tells me to go this URL.  See screenshot:
![device-2016-10-28-094135](https://cloud.githubusercontent.com/assets/201209/19808415/c151e378-9cf2-11e6-9b33-32ece89915cf.png)

What am I doing wrong?

Igor

**Comment by dtmilano** [comment]
Hi Igor,
Thanks for reporting.
To help me help you better please follow the steps in **Report and issue** in https://github.com/dtmilano/CulebraTester-public.
