### ISSUE TITLE
RuntimeError [111] on Debian

### ISSUE THREAD

**Issue by Naarukarmic** [dtmilano/AndroidViewClient#211]
Hello,

Been fiddling for a while with the ViewClient to setup some automated tests for Android on the latest Debian distribution (x64).
I am using stock packages (ADB v 1.0.31, androidviewclient through easy_install).

My device shows as connected and ADB commands work.
However, when I either try to use _dump_ or establish a connection with:
_vc = ViewClient(*ViewClient.connectToDeviceOrExit())_
I am thrown the following lines, with the RuntimeError 111:

```
Traceback (most recent call last):
  File "/usr/local/bin/dump", line 4, in <module>
    __import__('pkg_resources').run_script('androidviewclient==12.3.0', 'dump')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1497, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-12.3.0-py2.7.egg/EGG-INFO/scripts/dump", line 206, in <module>
    vc = ViewClient(*ViewClient.connectToDeviceOrExit(**kwargs1), **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-12.3.0-py2.7.egg/com/dtmilano/android/viewclient.py", line 2692, in connectToDeviceOrExit
    device = adbclient.AdbClient(serialno, ignoreversioncheck=ignoreversioncheck, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-12.3.0-py2.7.egg/com/dtmilano/android/adb/adbclient.py", line 157, in __init__
    self.socket = AdbClient.connect(self.hostname, self.port, self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-12.3.0-py2.7.egg/com/dtmilano/android/adb/adbclient.py", line 217, in connect
    raise RuntimeError("ERROR: Connecting to %s:%d: %s.\nIs adb running on your computer?" % (s, port, ex))
RuntimeError: ERROR: Connecting to <socket._socketobject object at 0x7f5305c7f6e0>:5037: [Errno 111] Connection refused.
Is adb running on your computer?
```

I see adb running using _ps aux | grep adb_, but when using the netstat command from a previous issue in this repo (https://github.com/dtmilano/AndroidViewClient/issues/208) I get nothing.

If you have any pointers, I'd gladly take them! 
Thanks a lot.

PS: I got the exact same setup to run in Windows, but I need Debian for USB-related stuff.

**Comment by Naarukarmic** [comment]
Indeed, thank you.
Installing the latest ADB version (1.0.36) fixed the issue - might need to add that somewhere in the Installation wiki. You have to do it manually from the Android SDK though.

Closing the issue.

**Comment by dtmilano** [comment]
Thanks for the info. I will add it to the *Installation* section.

**Comment by LagunaMatada** [comment]
@Naarukarmic Where did you find the adb version (1.0.36) for raspbien?

**Comment by Naarukarmic** [comment]
@LagunaMatada My issue was with Debian and not Raspbian sadly, I solved it by getting the latest binaries from https://developer.android.com/studio/index.html#downloads
You should however be able to adapt the script you found to the latest versions of the ADB tools - I see no reason it wouldn't compile. If you look at the forks on the project you linked, some people did indeed install newer versions.
