### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by se0da1n** [dtmilano/AndroidViewClient#212]
Hello,

I have installed AndroidViewClient by the following command

sudo easy_install --upgrade androidviewclient

It seems to work fine because culebra and dump files are installed in /usr/local/bin/
But I can not find installed AndroidViewClient directory which has as 'examples' and 'src'

Should I more run commands??

This is my logs when installed

$ sudo easy_install --upgrade androidviewclient
[sudo] password for : 
Searching for androidviewclient
Reading http://pypi.python.org/simple/androidviewclient/
Best match: androidviewclient 12.4.0
Downloading https://pypi.python.org/packages/8b/44/604e460e7c3f9266dbffdf90b90e3e42a493700c8e11bd89417ebc8757b9/androidviewclient-12.4.0-py2.7.egg#md5=5173da66bd52c200b640930e36826e3e
Processing androidviewclient-12.4.0-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/androidviewclient-12.4.0-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/androidviewclient-12.4.0-py2.7.egg
Extracting androidviewclient-12.4.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
androidviewclient 12.4.0 is already the active version in easy-install.pth
Installing culebra script to /usr/local/bin
Installing dump script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/androidviewclient-12.4.0-py2.7.egg
Processing dependencies for androidviewclient
Finished processing dependencies for androidviewclient

**Comment by dtmilano** [comment]
Source and examples are not in the installed package.
You should download the zip file https://github.com/dtmilano/AndroidViewClient/archive/master.zip or clone https://github.com/dtmilano/AndroidViewClient.git with git.

**Comment by se0da1n** [comment]
Thank you, I found it :)
