### ISSUE TITLE
Can I check status of view?

### ISSUE THREAD

**Issue by se0da1n** [dtmilano/AndroidViewClient#213]
Hello,

First, thank you for the nice tool

By any chance, Can I check status of view??
If checkbox is checked, or radio button is selected, can I know it after find view??
If it can, could you guide simple code?? (I know basic usage of this tool)

Thank you

**Comment by se0da1n** [comment]
In my investigation, this could be useful.

    view = vc.findViewById('id_of_view')
    if view:
        print view.map['checked']

and I could check other attributes by this

    view = vc.findViewById('id_of_view')
    if view:
        print view.__str__()

**Comment by dtmilano** [comment]
A Checkbox's state can be tested as

```
print "checked:", vc.findViewWithText(u'Checkbox 1').isChecked()
```

and a RadioButton like

```
print "selected:", vc.findViewWithText(u'RadioButton 1').isChecked()
```

**Comment by se0da1n** [comment]
That API looks more useful. 
Thank you for guide :)
