### ISSUE TITLE
waiting device to connect

### ISSUE THREAD

**Issue by se0da1n** [dtmilano/AndroidViewClient#214]
Hi,

when I use the following function to connect device,

**ViewClient.connectToDeviceOrExit(verbose=True, ignoreversioncheck=True)**

I expected that function waits device for timeout value(60 sec) if device list is not ready because it is booting
But I met the following exception immediately

**Connecting to a device with serialno=.* with a timeout of 60 secs...
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    ViewClient.connectToDeviceOrExit(verbose=True, ignoreversioncheck=True)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-12.4.0-py2.7.egg/com/dtmilano/android/viewclient.py", line 2692, in connectToDeviceOrExit
    device = adbclient.AdbClient(serialno, ignoreversioncheck=ignoreversioncheck, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-12.4.0-py2.7.egg/com/dtmilano/android/adb/adbclient.py", line 171, in __init__
    self.__setTransport()
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-12.4.0-py2.7.egg/com/dtmilano/android/adb/adbclient.py", line 327, in __setTransport
    raise RuntimeError("ERROR: There are no connected devices")
RuntimeError: ERROR: There are no connected devices**

also, I tried to check connection status like below

**device = AdbClient()
if device.checkConnected() == True:
     print "connected!"**

But It always returns 'True' even adb could not connect device during booting time
I tested it immediately after booting starts_

Is there any way to wait device??

Thank you

**Comment by danafergan** [comment]
Can you either sleep for a sufficient time to let the device boot, or loop until adb devices returns a device?

import subprocess

then process the output of 
subprocess.check_output('adb devices', shell=True)
until you see the device you want

**Comment by danafergan** [comment]
Can you either sleep for a sufficient time to let the device boot, or loop until adb devices returns a device?

`import subprocess`

then process the output of
`subprocess.check_output('adb devices', shell=True)`
until you see the device you want

**Comment by danafergan** [comment]
Can you either sleep for a sufficient time to let the device boot, or loop until adb devices returns a device before trying to connect it?

`import subprocess`

then process the output of
`subprocess.check_output('adb devices', shell=True)`
until you see the device you want

**Comment by se0da1n** [comment]
Thank you for answer

I have solved this by this


import os

os.system('adb wait-for-device')

**Comment by dtmilano** [comment]
@se0da1n you were right, it's a bug I would say.
While @danafergan solution is perfectly valid, version **12.5.0** (see 7cb87b6c4289427ccd631617ccdeae6bbba716b6) handles the timeout correctly and now you can start with no connected devices and `AdbClient` waits until a device appears or timer expires

```
Connecting to a device with serialno=.* with a timeout of 120 secs...
Empty device list, will wait 120 secs for devices to appear
....
Connected to device with serialno=.*
Actual device serialno=xyz
```
