### ISSUE TITLE
adb server version doesn't match my client

### ISSUE THREAD

**Issue by luiscruz** [dtmilano/AndroidViewClient#216]
I can't run culebra generated code.

```
adb server version (32) doesn't match this client (36); killing...
* daemon started successfully *
Traceback (most recent call last):
  File "tata.py", line 36, in <module>
    vc.dump(window='-1')
  File "/Library/Python/2.7/site-packages/com/dtmilano/android/viewclient.py", line 3268, in dump
    received = self.device.shell(cmd)
  File "/Library/Python/2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 440, in shell
    self.__send('shell:%s' % cmd, checkok=True, reconnect=False)
  File "/Library/Python/2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 258, in __send
    self.__checkOk()
  File "/Library/Python/2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 295, in __checkOk
    recv = sock.recv(4)
socket.error: [Errno 54] Connection reset by peer
TIMEOUT HANDLER 39
Exception in thread Thread-40:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/com/dtmilano/android/adb/adbclient.py", line 194, in timeoutHandler
    raise Timer.TimeoutException("Timer %d has expired" % timerId)
TimeoutException: Timer 39 has expired
```

**Comment by dtmilano** [comment]
First of all, I think you have two conflicting versions of `adb` that's why one is killed.

What `adb`versions you have installed?

**Comment by dtmilano** [comment]
It will also be helpful if you post your script and if it was generated by [CulebraTester](http://culebra.dtmilano.com/) also the information required for a bug report as described in [CulebraTester-public](https://github.com/dtmilano/CulebraTester-public).

**Comment by luiscruz** [comment]
Hmm, I didn't know I could have conflicting versions of ```adb```.
I'll dig into this and I'll  come back with more info and a proper bug report.

**Comment by luiscruz** [comment]
Tested in another machine and everything works fine.
I still have to figure out how to fix this but definitely it is not related with AndroidViewClient.
Sorry for the hassle!

**Comment by dtmilano** [comment]
@luiscruz I have an idea of what could be happening. It seems from your messages that you have 2 different versions of `adb` installed and I guess `ViewClient` is finding the wrong one.

`ViewClient`'s constructor can receive an `adb` parameter

```python
def __init__(self, device, serialno, adb=None,...
```

and if it is `None` then `obtainAdbPath()` is used to find it. This method uses these locations to find `adb` on OS X (which I think is what you are using):

```python
        possibleChoices.append(os.path.join(HOME, "Library", "Android", "sdk", 'platform-tools', adb))
        possibleChoices.append(os.path.join(os.sep, "opt", "android-sdk-mac_x86", 'platform-tools', adb))
        possibleChoices.append(os.path.join(HOME, "opt", "android-sdk-mac", 'platform-tools', adb))
        possibleChoices.append(os.path.join(HOME, "android-sdk-mac", 'platform-tools', adb))
        possibleChoices.append(os.path.join(HOME, "opt", "android-sdk-mac_x86", 'platform-tools', adb))
        possibleChoices.append(os.path.join(HOME, "android-sdk-mac_x86", 'platform-tools', adb))
```

the problem may be that one of these locations actually exists.

**Comment by luiscruz** [comment]
It was exactly my problem — I had conflicting installations of sdks.
All set! Thanks @dtmilano.
