### ISSUE TITLE
OS X Installation Instructions

### ISSUE THREAD

**Issue by DVassilev** [dtmilano/AndroidViewClient#220]
I'm having issues getting this running on OS X. I used easy_install to install it which worked. I then tried to run the GUI but kept telling me to install Pillow (even after doing so successfully using pip). I tried the `from PIL import Image, ImageTk` and found there was an issue with Tk as got the error `import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named _tkinter`.

I uninstalled Python using Brew and installing ActivePython. I then modified `/usr/local/bin/culebra` to use `/usr/local/bin/python` instead of it's current config to look for python. I then installed AndroidViewClient again and tried to run it, however still get `Exception: PIL or Pillow is needed for GUI mode`. I tried running the commands manually in python and they now import successfully so I'm hoping someone could shed some light on why this isn't working.

Thanks

**Comment by dtmilano** [comment]
Can you please add more details about the versions of the software you are using?
(OS X, python, etc.)

I certainly don't have this problem and use OS X regularly.
Are you sure you are using python 2.x instead of 3?

**Comment by DVassilev** [comment]
@dtmilano I am using ActivePython 2.7.13.2713 and OS X 10.11.5. Perhaps you could give instructions on what you did to set up your environment? (ie. how you installed python etc.)
