### ISSUE TITLE
Possible typo in ViewClient: DEVIDE

### ISSUE THREAD

**Issue by krissrex** [dtmilano/AndroidViewClient#223]
I assume these two are misspellings of DEVICE: [one](https://github.com/dtmilano/AndroidViewClient/blob/8435bf732c5463299c9a39223056f71b844fca48/src/com/dtmilano/android/viewclient.py#L2348), [two](https://github.com/dtmilano/AndroidViewClient/blob/8435bf732c5463299c9a39223056f71b844fca48/src/com/dtmilano/android/viewclient.py#L2432).

I don't have the project checked out, so I can't look for occurrences in other files and submit a PR.

**Comment by dtmilano** [comment]
Good catch. Thanks.
