### ISSUE TITLE
takeSnapshot hangs on Nexus 7.1+ when app actively blocks snapshots

### ISSUE THREAD

**Issue by meirtsvi** [dtmilano/AndroidViewClient#225]
In order to repro the crash use the following:

1. Install SAP fiori client ver. 1.6.3 - http://www.apkmonk.com/app/com.sap.fiori.client/ on nexus with android 7.1 (or newer) device.
2. Open the app
3 Run the script from: https://github.com/dtmilano/AndroidViewClient/files/368494/run.txt

Expected result: a png file should be created
Actual result: takeSnapshot never returns

I'm using the latest viewclient package

**Comment by dtmilano** [comment]
Can you reproduce the issue on emulator or on a different device?

**Comment by meirtsvi** [comment]
Yes, it also happens on Android Emulator with Nexus 5X API 25 (Android 7.1.1) image.

**Comment by dtmilano** [comment]
![screen shot 2017-06-15 at 01 21 52](https://user-images.githubusercontent.com/982482/27214551-21608abe-523b-11e7-93d4-e218c3d9c608.png)

The same happens if you try to get the screenshot with Android Studio as the app is not allowing it.

**Comment by meirtsvi** [comment]
My problem is that viewclient is STUCK on reading from socket. I have no problem putting try/except around takeSnapshot but in this case it is just getting stuck rather than throwing exception.

**Comment by dtmilano** [comment]
Understood. Will look for a solution.

**Comment by meirtsvi** [comment]
Thank you

**Comment by meirtsvi** [comment]
Works like a charm. Thank you!
