### ISSUE TITLE
what version of adb does viewclient support?

### ISSUE THREAD

**Issue by jacree** [dtmilano/AndroidViewClient#227]
I'm trying to run view client on our android application but on a very old version of adb. I'm trying to control the menu screen remotely from ubuntu linux. When  I run the foloowing code, it can find the help button but it will not press to proceed to the next screen. The version of adb I am using is:
harleyj700@harleyj700-PORTEGE-R835:~$ adb shell getprop ro.build.version.sdk
10
harleyj700@harleyj700-PORTEGE-R835:~$ adb shell getprop ro.build.version.release
2.3.4

The following has not been working for me so I am wondering is it the fact I am on version 10

import sys
import os
import time
sys.path.append(os.environ['ANDROID_VIEW_CLIENT_HOME'])
from com.dtmilano.android.viewclient import ViewClient, View, ViewClientOptions, ViewNotFoundException

def main():
        def Connect_View_Client(id):
                kwargs = {}
                print "Connect_View_Client: id = " + str(id)
                device, serialno = ViewClient.connectToDeviceOrExit(serialno=str(id), **kwargs)
                vc = ViewClient(device, serialno, **kwargs)
                return vc

        vc = Connect_View_Client(20120629)
        vc.dump()
        print "vc = " + str(vc)
        id_helpButton = vc.findViewByIdOrRaise("id/helpButton")
        print "id_helpButton = " + str(id_helpButton)
        id_helpButton.touch()
        #val.touch()
        #vc.sleep(5)
        #vc.dump()
        #val1 = vc.findViewById('id/outofProduct')
        #print "val1 = " + str(val1)
        #vc.sleep(5)

if __name__ == '__main__':
        main()

**Comment by dtmilano** [comment]
Hi Jeff,
Can you provide the output?
Is id_helpButton found?

**Comment by jacree** [comment]
Hi,
When I do dump, the button is found. It also doesn’t complain when I do vc.touch() the object. If I do a non existent button, it does complain so I knw it sees the device buttons

harleyj700@harleyj700-PORTEGE-R835:~/Documents/touchscreen$ dump
com.android.internal.policy.impl.PhoneWindow$DecorView NO_ID
   android.widget.FrameLayout id/content
      android.widget.RelativeLayout NO_ID
         android.widget.LinearLayout id/linearLayout
            android.widget.LinearLayout NO_ID
               android.widget.Button id/redeemButton REDEEM
               android.widget.Button id/nutritionButton NUTRITION
            android.widget.LinearLayout NO_ID
               android.widget.Button id/helpButton HELP
         com.usatech.mediaview.MediaView id/mediaView
            android.widget.ImageView id/imageview_id
            android.widget.VideoView id/videoview_id
         android.widget.LinearLayout id/disabledLayout
            android.widget.TextView id/textView13 Device Not Enabled
            android.widget.TextView id/textView11 Please try again later

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dtmilano** [comment]
First of all, you are right AndroidViewClient should tell that `touch()` does not work on API 10 because the `input` command does not support touch in those versions (I'm fixing it).

The only solution I can think of came from [Android Application Testing Guide](http://www.packtpub.com/android-application-testing-guide/book) page 143, something that I have almost forgotten ;-)

There's a lot of room for improvement but you can do

```python
x, y = id_helpButton_toggle.getCenter()
device.shell("monkey --port 9997 & sleep 1; echo -e 'tap %d %d\nquit' | nc localhost 9997" % (x, y))
```
