### ISSUE TITLE
Cannot get a correct screenshot when an app only works under landscape mode

### ISSUE THREAD

**Issue by gchen36** [dtmilano/AndroidViewClient#229]

**Comment by dtmilano** [comment]
Do you have an example you could share?

**Comment by gchen36** [comment]
<img width="497" alt="screen shot 2017-11-15 at 1 09 49 pm" src="https://user-images.githubusercontent.com/2905460/32852601-6cec22b6-ca06-11e7-8fde-a9d7770ae762.png">
![www studiolassa nl backyardbrawl-10](https://user-images.githubusercontent.com/2905460/32852653-a74f302e-ca06-11e7-9560-0194624adc95.png)

The issue is related to writeImageToFile(). I wanted to get the ad image which correctly locates at ((0, 949), (1794, 1080)); however, I got the enclosed image file.

**Comment by gchen36** [comment]
<img width="497" alt="screen shot 2017-11-15 at 1 09 49 pm" src="https://user-images.githubusercontent.com/2905460/32852938-9b6f33b6-ca07-11e7-8b8b-4a6ae850fc7e.png">

**Comment by gchen36** [comment]
The issue is related to writeImageToFile(). I wanted to get the ad image which correctly locates at ((0, 949), (1794, 1080)); however, I got the enclosed image file.
![www studiolassa nl backyardbrawl-10](https://user-images.githubusercontent.com/2905460/32852949-a6cc06bc-ca07-11e7-86c5-829ad3bf0a0c.png)

**Comment by gchen36** [comment]
<img width="504" alt="screen shot 2017-11-15 at 1 21 38 pm" src="https://user-images.githubusercontent.com/2905460/32853168-6c89a350-ca08-11e7-95a7-bd8f89f1bd8f.png">

**Comment by gchen36** [comment]
The issue is related to writeImageToFile(). I wanted to get the ad image which locates at ((0, 949), (1794, 1080)); however, I got the enclosed image file.
![www studiolassa nl backyardbrawl-10](https://user-images.githubusercontent.com/2905460/32853195-810f5e3c-ca08-11e7-88fe-5c2d3ecf099f.png)

**Comment by dtmilano** [comment]
Have you tried a real device?
I think the problem might be that the emulator is in *portrait* mode while the application is in *landscape*. On a real device, this might not happen.

**Comment by gchen36** [comment]
I just tested by commenting out image.crop(box).save(filename, _format) in viewclient.py, the issue comes from uiautomator.takeScreenshot() on genymotion.
![www studiolassa nl backyardbrawl-10](https://user-images.githubusercontent.com/2905460/32871796-29a677e0-ca51-11e7-8748-bee48e32e5f4.png)
