### ISSUE TITLE
Touch DOWN and Touch UP has the same behavior as Touch DOWN_AND_UP

### ISSUE THREAD

**Issue by lucviala** [dtmilano/AndroidViewClient#231]
When I tried to Touch down and/or touch up a button, adb logcat gives me pressed button and released button instantly
`
ROBOT_LIBRARY_SCOPE = "GLOBAL"

def __init__(self, serialno):
	if not serialno.isalnum():
                raise Exception
	kwargs1 = {'ignoreversioncheck': True, 'verbose': True, 'ignoresecuredevice': True}
	kwargs2 = {'forceviewserveruse': False, 'useuiautomatorhelper': False, 'ignoreuiautomatorkilled': True,
					'autodump': False, 'startviewserver': False, 'compresseddump': True}
	device,  serialno = ViewClient.connectToDeviceOrExit(serialno=serialno, **kwargs1)
	self.vc = ViewClient(device, serialno, **kwargs2)
	self.device = device
	self.serialno = serialno
	self._usr = None
	self.activity = None
	self._view = None
	self.adbClient = AdbClient(self.serialno)
	logger.info("ViewClientWrapper: connected to:\t%s" % self.device)
...	
def user_touch_down_button(self):
	self.vc.dump()
	view = self.vc.findViewByIdOrRaise(btn)
	if view:
                center = view.getCenter()
		logger.console(center)
		self.device.touch(center[0], center[1], eventType=AdbClient.DOWN)

	
def user_touch_up_button(self):
	self.vc.dump()
	view = self.vc.findViewByIdOrRaise(btn)
	if view:
                center = view.getCenter()
		logger.console(center)
		self.device.touch(center[0], center[1], eventType=AdbClient.UP)
`

**Comment by dtmilano** [comment]
Can you tell what Android version and device you are using?

**Comment by Blobby19** [comment]
I'm working on Samsung Galaxy A5 running Android 6.0.1

**Comment by dtmilano** [comment]
Are you trying to simulate a *long touch* or something else?

**Comment by Blobby19** [comment]
When button is down the application have to push me some informations through the network and stop when button is up. I need to verify informations pushed through the network before release the button. I already implement the longTouch action but it forces me to use threads to check informations received between down and up or check informations through a buffer after released button.

**Comment by Proficus** [comment]
Fixed?
