### ISSUE TITLE
Is ImageView Supported ?

### ISSUE THREAD

**Issue by Blobby19** [dtmilano/AndroidViewClient#234]
Hello,

I'm facing issues with ImageView, I unable to find them using findView methods it raises me exception.

And also when ImageViews are in ListView I can't get them using getChildrens method.

**Comment by dtmilano** [comment]
Can you provide some examples?
Also, the device and versions used would be helpful.

**Comment by Blobby19** [comment]
The following code is extracted with uiautomatorviewer :
`<node index="1" text="" resource-id="id_view_list" class="android.support.v7.widget.RecyclerView" package="..." content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,549][1080,1920]">
    <node index="0" text="" resource-id="" class="android.widget.LinearLayout" package="..." content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[0,549][1080,717]">
        <node index="0" text="" resource-id="id_icon_check" class="android.widget.ImageView" package="..." content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[48,597][120,669]" />
        <node index="1" text="Text 1" resource-id="id_text" class="android.widget.TextView" package="..." content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[168,599][1032,667]" />
    </node>
    <node index="1" text="" resource-id="" class="android.widget.LinearLayout" package="..." content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[0,717][1080,885]">
        <node index="0" text="Text 2" resource-id="id_text" class="android.widget.TextView" package="..." content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[168,767][1032,835]" />
    </node>
</node>`

And this one is dump using AndroidViewClient :
`android.support.v7.widget.RecyclerView id_view_list 
      android.widget.LinearLayout  
         android.widget.TextView id_text Text 1
      android.widget.LinearLayout  
         android.widget.TextView id_text Text 2`

Android device is Samsung Galaxy A5 in version 6.0.1

**Comment by dtmilano** [comment]
If I dump Google Play Store (as I don't know the app you are using), `ImageViews` inside the `RecyclerView` are displayed without a problem

                 android.widget.RelativeLayout com.android.vending:id/play_card 
                     android.widget.ImageView com.android.vending:id/li_overflow 
                     android.view.View com.android.vending:id/li_rating 
                     android.view.View com.android.vending:id/li_label 
                  android.widget.RelativeLayout com.android.vending:id/play_card 
                     android.widget.TextView com.android.vending:id/li_title XXXXX
                     android.widget.ImageView com.android.vending:id/li_overflow 
                     android.view.View com.android.vending:id/li_rating 
                     android.view.View com.android.vending:id/li_label 
                  android.widget.RelativeLayout com.android.vending:id/play_card 
                     android.widget.TextView com.android.vending:id/li_title XXXXX
                     android.widget.ImageView com.android.vending:id/li_overflow 
                     android.view.View com.android.vending:id/li_rating 
                     android.view.View com.android.vending:id/li_label
