### ISSUE TITLE
Error while installing AndroidViewClient

### ISSUE THREAD

**Issue by Divya063** [dtmilano/AndroidViewClient#235]
I was getting this error `ImportError: No module named extern` while running the command `sudo easy_install --upgrade androidviewclient`. I used this command  `sudo python -m pip install --upgrade pip setuptools wheel` before running the `sudo easy_install --upgrade androidviewclient` command and the  error was rectified. Maybe this should be added in the documentation?

**Comment by dtmilano** [comment]
Thanks for your comment.
What was the OS?
Python version?
virtualenv?

**Comment by Divya063** [comment]
I'm on Ubuntu and python version is 2.7

**Comment by dtmilano** [comment]
Better stay with your package manager

    $ sudo apt install python-pip-whl python-setuptools
