### ISSUE TITLE
Both dump tool and vc.dump() fails on “PLAYING FROM PLAYIST” screen while “Spotify” app is playing music

### ISSUE THREAD

**Issue by yamatakau08** [dtmilano/AndroidViewClient#238]
Dear dtmilano,

While “Spotify” app is playing music on “PLAYING FROM PLAYLIS” screen,
I call “vc.dump()”, it always **FAILS.**

Do you have any idea to get success vc.dump or have any option?
The root cause seems to be the progress is moving bar on screen?
But another app have the playing progress bar, dump tool **DOES NOT** fail!

[vc.dump from my script]
```
  File "MySpotify.py", line 313, in screen_MAIN
    vc.dump()
  File "C:\temp\AndroidViewClient-13.6.2\src\com\dtmilano\android\viewclient.py", line 3318, in dump
    raise RuntimeError('''The views are being refreshed too frequently to dump.''')
RuntimeError: The views are being refreshed too frequently to dump.
```

[tools dump]
On the same screen, dump command also always fails
```
c:\temp\AndroidViewClient-13.6.2\tools>python dump
Traceback (most recent call last):
  File "dump", line 230, in <module>
    vc.dump(window=options[WINDOW])
  File "C:\temp\AndroidViewClient-13.6.2\src\com\dtmilano\android\viewclient.py", line 3318, in dump
    raise RuntimeError('''The views are being refreshed too frequently to dump.''')
RuntimeError: The views are being refreshed too frequently to dump.
```
The screen is the following
![screen](https://user-images.githubusercontent.com/13044987/35432485-967fecfc-02c3-11e8-94ae-38c18f4d65c7.JPG)

**Comment by dtmilano** [comment]
**AndroidViewClient/culebra** uses `uiautomator dump` to obtain the tree of Views and unfortunately, there is a limitation in this tool and the tree cannot be obtained while the screen is being updated what happens when an application like Spotify is constantly updating the screen.

**CulebraTester** (http://culebra.dtmilano.com/) a similar tool which uses a different method to obtain the Views can do it. I tried Spotify and there's no problem, so I think it may help you.

This screenshot shows the tree and the seekbar highlighted.
![culebra - google chrome_150](https://user-images.githubusercontent.com/982482/35469122-6ef0894c-02fc-11e8-86df-f2302543cf99.png)

**Comment by yamatakau08** [comment]
Dear Diego,

> ... there is a limitation in this tool 
> CulebraTester ... obtain the Views can do it. ..
Is it possible to call Culebra api to obtain view and use them instead of vc.dump() from AndroidViewClient.
If possible, could you provide me a sample code.

And then,
Thank you for the alternative tool "CulebraTest".
Later I'll try it.

**Comment by dtmilano** [comment]
Yes, it's possible.
Let me clarify what you want to do: you want to obtain the dump (as the output of the script) that same as you are obtaining from `python dump`

**Comment by yamatakau08** [comment]
Dear Diego,

My script is in the following repository.
[https://github.com/yamatakau08/MySpotifyTestScript](url)
file: Question.py
line 137 to 142
```
print 'Touch "btn_play”'
Playing(vc,SCMD_PLAY)

vcsleep(7)

print 'Open "Connect to a device" screen'
Playing(vc,SCMD_CONNECT)
```
have the following RuntimeError.
```
File "Playing.py", line 66, in Playing
vc.dump()
File "/Users/yama/Library/python/AndroidViewClient/src/com/dtmilano/android/viewclient.py", line 3318, in dump
raise RuntimeError('''The views are being refreshed too frequently to dump.'’')
```
Could you teach me how to use the Culebra dump method in AndroidViewClient script to avoid this RuntimeError?

**Comment by dtmilano** [comment]
I created a pull request: https://github.com/yamatakau08/MySpotifyTestScript/pull/1/commits/9b9b022e251c0b496f2a72d84f52ad698fa1bfd3
containing the changes.

Once I run the script, I get this results

```
$ ./Question.py 
Start component:"com.spotify.music/.MainActivity"
Screen title: "Home"
Touch "home_tab" to back "Home"
Open Playing screen
Touch "btn_play"
"com.spotify.music:id/btn_play" touch!
ViwewClient.sleep(7)
Touch "btn_play"
"com.spotify.music:id/btn_play" touch!
ViwewClient.sleep(7)
Open "Connect to a device" screen
Closing
```

which I understand are as expected.

**Comment by dtmilano** [comment]
I also created [spotify.py](https://github.com/dtmilano/AndroidViewClient/blob/master/examples/culebratester/soptify.py) which shows how you can create a test script that does the same just by interacting with the device using [CulebraTester](http://culebra.dtmilano.com/).

These scripts are compatible with the ones you were accustomed to creating, so you can mix and match.

**Comment by yamatakau08** [comment]
Thank you for your pull request.
That's just what I wanted to do.
I appreciate your support.
