### ISSUE TITLE
Culebra cmd line functionality appears broken as of v14+ (mac)

### ISSUE THREAD

**Issue by ktkopone** [dtmilano/AndroidViewClient#240]
Doing a `pip install androidviewclient==13.6.3` nets normal output for the cmd line `culebra [serialno]` view dumper.

Using `pip install androidviewclient==14.0.0` or up to the current version results in `culebra [serialno]` attempting to find a non-existent `/Users/diego/` directory - there must be a hardcoded path somewhere.

**Comment by ktkopone** [comment]
culebra now fails on line 39 with 'No module named com.dtmilano.android.viewclient' - although that import works fine in my python shell, and I can confirm that doing the same install with 13.6.3 leaves culebra working fine.

**Comment by dtmilano** [comment]
Try using

    easy_install --upgrade androidviewclient

as described [here](https://github.com/dtmilano/AndroidViewClient/wiki#using-easy_install)

**Comment by ktkopone** [comment]
Had to uninstall and reinstall setuptools (in spite of it being the latest version), but in the end I got that command to run and culebra now works fine.

Even after the setuptools reinstall the pip command was still breaking culebra, so it looks like easy_install might be the only way to install for now, or else something in my system is weird.

Thanks for the help!

**Comment by dtmilano** [comment]
@ktkopone right, I think `pip` cannot handle correctly package names like `com.dtmilano.android...`
