### ISSUE TITLE
How to locate and click the element in popupwindow.

### ISSUE THREAD

**Issue by QingXiangBaiLian** [dtmilano/AndroidViewClient#241]
I can't locate the elements in popupwindow via findViewWithText or findViewWithTextOrRaise method, and there are many elements need to be click, thus I can't measure all the locations manually.

**Comment by dtmilano** [comment]
Can you please provide more context for your problem.
How the layout looks like?
Sceeenshot, intentions, etc.

**Comment by QingXiangBaiLian** [comment]
As our app is still under developing, for business secrecy is not convenient to display here。So I give an equivalent description using another app as follows. the problem is I want to detect all the elements in the popupwindow automatically and click some of them，like the button ‘男’ and '女' in the bellow picture
![1](https://user-images.githubusercontent.com/20887685/38721086-5c286cba-3f2b-11e8-8ddc-3ffb512d7f2a.png)
As these buttons were in the popupwindow, I can't get them via getting the `page_source` using appium，even couldn't be detect by uiautomatorviewer，but I can find them in the hierarchyviewer as showed below
![2](https://user-images.githubusercontent.com/20887685/38721410-a9749ba0-3f2c-11e8-9366-12feb174a29e.png)
Could I using AndroidViewClient to get all the elements in the popupwindow and click them? I have used Culebra GUI, however the generated code using `self.device.touchDip()` method to click the button's coordinates directly instead of detect the button first. this question have boring me for a week, any other method is also welcomed, very thanks!
By the way, change the App's source code is impossible.

**Comment by QingXiangBaiLian** [comment]
@dtmilano 
Very thanks for your quick reply！
As our app is still under developing, for business secrecy is not convenient to display here。So I give an equivalent description using a Demo as follows. The problem is I want to detect all the elements in the PopupWindow automatically and click some of them，like the button ‘A’ , 'B' and 'C' in the bellow picture
![image](https://user-images.githubusercontent.com/20887685/38732894-88fd03c8-3f52-11e8-82bd-e59c5d14c376.png)
As these buttons were in the PopupWindow, I can't get them via getting the `page_source` using appium，even couldn't be detect by uiautomatorviewer，but I can find them in the hierarchyviewer.
 This question have boring me for a week,  I have used Culebra GUI, however the generated code using `self.device.touchDip()` method to click the button's coordinates directly instead of detect the button first. 
And now, I have made a big forward.  At the beginning I using `vc.dump(-1)` to dump all the window then using `vc.findViewWithText(u'A') `to find the Button A, it return None. But if I only dump the PopupWindow (Given the ID, such as 123, then `vc.dump(123)` ), it turns out that I can find the Button A.  And I can using vc.list() to get all the window IDs and names, then find the PopupWindow's ID. but I still struggle to list all the elements' Text after dump the PopupWindow, I know vc.traverse() can print the Text, but I want to return the  Text, then using that in `vc.findViewWithText()`.

**Comment by dtmilano** [comment]
By default, **AndroidViewClient/culebra** relies on the Views included in the tree produced by `uiautomator dump` (backend) and as you have verified already, it doesn't contain Views from other windows.

**AndroidViewClient/culebra** has the ability to use other backends. You should have been using *ViewServer* as you were dumping the content of other windows. It might be possible to find a solution but *ViewServer* is old and does not run in secure mode (see [wiki](https://github.com/dtmilano/AndroidViewClient/wiki/Secure-mode)).

There's still another backend, the newest one, called *uiautomatorhelper* or **CulebraTester**. Which I'm describing here via an example similar to your case.
 
**CulebraTester** details can be found at [culebra.dtmilano.com](http://culebra.dtmilano.com/).

Once you have the 2 APKs installed on your device (see [Getting started](https://github.com/dtmilano/CulebraTester-public/wiki/Getting-started)), you start it and open the page with your desktop browser.

![screen shot 2018-04-14 at 02 07 31](https://user-images.githubusercontent.com/982482/38765277-80114276-3f8c-11e8-8683-3a1f25df773f.png)

In this case, I'm using a demo app that shows a `PopupWindow`.
You can verify that the **DISMISS** button appears in the hierarchy, and when you click it, the generated test includes the line to select and click it.

The complete generated test is

```python
#! /usr/bin/env python
# -*- coding: utf-8 -*-
'''
Copyright (C) 2013-2018  Diego Torres Milano
Created on 2018-04-14 by CulebraTester 
                      __    __    __    __
                     /  \  /  \  /  \  /  \ 
____________________/  __\/  __\/  __\/  __\_____________________________
___________________/  /__/  /__/  /__/  /________________________________
                   | / \   / \   / \   / \   \___
                   |/   \_/   \_/   \_/   \    o \ 
                                           \_____/--<
@author: Diego Torres Milano
@author: Jennifer E. Swofford (ascii art snake)
'''


import re
import sys
import os


import unittest
try:
    sys.path.insert(0, os.path.join(os.environ['ANDROID_VIEW_CLIENT_HOME'], 'src'))
except:
    pass

import pkg_resources
pkg_resources.require('androidviewclient>=12.4.0')
from com.dtmilano.android.viewclient import ViewClient, CulebraTestCase
from com.dtmilano.android.uiautomator.uiautomatorhelper import UiAutomatorHelper, UiScrollable, UiObject, UiObject2

TAG = 'CULEBRA'


class CulebraTests(CulebraTestCase):

    @classmethod
    def setUpClass(cls):
        cls.kwargs1 = {'ignoreversioncheck': False, 'verbose': False, 'ignoresecuredevice': False}
        cls.kwargs2 = {'forceviewserveruse': False, 'useuiautomatorhelper': True, 'ignoreuiautomatorkilled': True, 'autodump': False, 'startviewserver': True, 'compresseddump': True}
        cls.options = {'start-activity': None, 'concertina': False, 'device-art': None, 'use-jar': False, 'multi-device': False, 'unit-test-class': True, 'save-screenshot': None, 'use-dictionary': False, 'glare': False, 'dictionary-keys-from': 'id', 'scale': 1, 'find-views-with-content-description': True, 'window': -1, 'orientation-locked': None, 'save-view-screenshots': None, 'find-views-by-id': True, 'log-actions': False, 'use-regexps': False, 'null-back-end': False, 'auto-regexps': None, 'do-not-verify-screen-dump': True, 'verbose-comments': False, 'gui': False, 'find-views-with-text': True, 'prepend-to-sys-path': False, 'install-apk': None, 'drop-shadow': False, 'output': None, 'unit-test-method': None, 'interactive': False}
        cls.sleep = 5

    def setUp(self):
        super(CulebraTests, self).setUp()

    def tearDown(self):
        super(CulebraTests, self).tearDown()

    def preconditions(self):
        if not super(CulebraTests, self).preconditions():
            return False
        return True

    def testSomething(self):
        if not self.preconditions():
            self.fail('Preconditions failed')

        _s = CulebraTests.sleep
        _v = CulebraTests.verbose

        self.vc.uiAutomatorHelper.findObject(bySelector='res@com.dtmilano.android.demoapplication:id/dismiss,clazz@android.widget.Button,text@DISMISS,package@com.dtmilano.android.demoapplication').clickAndWait(eventCondition='until:newWindow', timeout=_s*1000)


if __name__ == '__main__':
    CulebraTests.main()
```

which when run and the popup is showing it clicks on the button and dismisses it.

**Comment by QingXiangBaiLian** [comment]
Very thanks for your answer, that's solved my question perfectly!
