### ISSUE TITLE
Script gets stuck on ViewClient(device, serial)

### ISSUE THREAD

**Issue by RebelKeithy** [dtmilano/AndroidViewClient#243]
If the device you are trying to connect to is disconnected between the lines
```
d, s = ViewClient.connectToDeviceOrExit()
device = ViewClient(d, s)
```
Then the script will never continue or give an error.

**Comment by dtmilano** [comment]
Interesting.
Do you disconnect the USB cable between those lines?

**Comment by RebelKeithy** [comment]
Yes, while testing for it that's what I did. 
I have a Raspberry Pi running tests and a phone, and for some reason the phone seems to randomly reconnect to the Pi sometimes, and that seemed to be causing the tests to get stuck.

**Comment by dtmilano** [comment]
@RebelKeithy let me know if it's fixed
