### ISSUE TITLE
Can't dump-simple.py determine widget's clickability?

### ISSUE THREAD

**Issue by jihunim** [dtmilano/AndroidViewClient#248]
I want to make a clickable elements tree for the current page. 
Can I do that with dump-simple.py?

Plus, how can I check two dumped results are the same page?

**Comment by dtmilano** [comment]
You can do something like this

```
for v in vc.dump():
    if v.isClickable():
        print v
```

**Comment by jihunim** [comment]
Thank you!

**Comment by jihunim** [comment]
Could you check my second question here?

> Plus, how can I check two dumped results are the same page?

For example, 
`def isIdenticalPage(page1, page2):
    if page1 is similar to page2:
        return True
    else
        return False`

**Comment by dtmilano** [comment]
There are several methods to calculate the distance between dumps, take a look at

- [ViewClient.distanceTo()](https://github.com/dtmilano/AndroidViewClient/blob/master/src/com/dtmilano/android/viewclient.py#L4152)
- [ViewClient.distance()](https://github.com/dtmilano/AndroidViewClient/blob/master/src/com/dtmilano/android/viewclient.py#L4163)
- [ViewClient.hammingDistance()](https://github.com/dtmilano/AndroidViewClient/blob/master/src/com/dtmilano/android/viewclient.py#L4217)
- [ViewClient.leveshteinDistance()](https://github.com/dtmilano/AndroidViewClient/blob/master/src/com/dtmilano/android/viewclient.py#L4308)

**Comment by jihunim** [comment]
Thank you for the information
