### ISSUE TITLE
Can this program feedback crash?

### ISSUE THREAD

**Issue by jihunim** [dtmilano/AndroidViewClient#249]
From the code here
```
b = vc.findViewWithText(bt)
b.touch()
```

Let's suppose that b.touch() triggers NullPointerException. Can I get the information that the exception has happened?

It looks not.

**Comment by dtmilano** [comment]
Perhaps you should use

```
b = vc.findViewWithTextOrRais(bt)
b.touch()
```

or simply

```
vc.findViewWithTextOrRaise().touch()
```

**Comment by jihunim** [comment]
That is not my point.
For example, during [UI/Application Exerciser monkey](https://developer.android.com/studio/test/monkey) testing, if a random touch makes subject application crash, **UI/Application Exerciser monkey** immediately stops the test and generate error report via **STDERR**
