### ISSUE TITLE
ImportError: No module named java

### ISSUE THREAD

**Issue by billunique** [dtmilano/AndroidViewClient#25]
Hi, 

I'm fresh to AndroidViewClient. When I ran dump.py on my Windows 7, I got an ImportError.  Message is as below:

D:\AndroidViewClient-master\AndroidViewClient\examples>dump.py -V
Traceback (most recent call last):
  File "D:\AndroidViewClient-master\AndroidViewClient\examples\dump.py", line 29
, in <module>
    from com.dtmilano.android.viewclient import ViewClient
  File "D:\AndroidViewClient-master\AndroidViewClient\src\com\dtmilano\android\v
iewclient.py", line 27, in <module>
    import java
ImportError: No module named java

I already set up the running environment, so what's wrong I got here?

Thanks very much in advance.

**Comment by jihunim** [comment]
@dtmilano , why don't you update your README [here](https://github.com/dtmilano/AndroidViewClient/wiki/culebra). it says "-j true" and it is confusing

**Comment by dtmilano** [comment]
@jihunim updated, thanks
