### ISSUE TITLE
dump() on android pie

### ISSUE THREAD

**Issue by subterfugium** [dtmilano/AndroidViewClient#257]
On android pie "adb shell uiautomator dump" command quite often produces
ERROR: null root node returned by UiTestAutomationBridge.
response.
Some discussion here: https://groups.google.com/forum/#!topic/android-testing-support-library/_yp04t8BC0M

I can see that this error has been also noticed here before:
https://github.com/dtmilano/AndroidViewClient/issues/58
I'm opening this ticket aware of the fact that this is not issue on androidviewclient. 

However, if there is already existing /sdcard/window_dump.xml file and "ERROR: null root node returned by UiTestAutomationBridge." issue happens, androidviewclient does not raise exception, but returns old results. I added self.device.shell('rm -r /sdcard/window_dump.xml') before self.viewclient.dump() and after that androidviewclient did raise expection (which is much better case than getting old results in response).

Issue here is that old results are returned if /sdcard/window_dump.xml exists instead of exception is raised. I am not able to grab logs currently, but I will try to do that later. I am not sure if adb shell uiautomator dump return this UTestAutomationBridge error via stdout or stderr or what is the return code.

**Comment by subterfugium** [comment]
There one report on google issue tracker on Pixel 2:
https://issuetracker.google.com/issues/111905752
1/5 dumps failed on pixel 2. google seem to ignore this issue.

**Comment by dtmilano** [comment]
For all of these cases where `uiautomator dump` fails [CulebraTester2-public](https://github.com/dtmilano/CulebraTester2-public) can be used as a back-end.
