### ISSUE TITLE
Find a child of a view in python UiAutomator API (without specifying view text or content description)

### ISSUE THREAD

**Issue by nicktgn** [dtmilano/AndroidViewClient#262]
Is it possible to search child views inside another view (UiObject or UiObject2) using python API?

Something like these two java functions of UiAutomator java API:
 - [UiObject2#findObject(bySelector)](https://developer.android.com/reference/android/support/test/uiautomator/UiObject2#findObject(android.support.test.uiautomator.BySelector))
 - [UiObject#getChild(uiSelector)](https://developer.android.com/reference/android/support/test/uiautomator/UiObject.html#getChild(android.support.test.uiautomator.UiSelector))

OR 

If this is not currently possible, is there any way to find a view inside the collection, if this view's text or description is unknown and the ID is not unique? Specific use case: find a particular view in a list and do assertion on its text.

This feature would be very useful.
Thanks in avance

**Comment by dtmilano** [comment]
https://github.com/dtmilano/CulebraTester2-public/commit/4d494f244479d3f7f065aaa5910b5fcc76f33554
