### ISSUE TITLE
findViewWithAttributeThatMatches only get one result

### ISSUE THREAD

**Issue by b10102016** [dtmilano/AndroidViewClient#265]
As title,

When called findViewWithAttributeThatMatches, only get one view. However, according to the result of  `dump -a`, there are more than one view that match the regexp.

Thanks

**Comment by dtmilano** [comment]
You can try

```
findViewsWithAttribute(attr, regex)
```

(notice the plural Views).

But you are right, and probably the method `findViewsWithAttributeThatMatches()` should be added.

**Comment by b10102016** [comment]
Thanks for updating
