### ISSUE TITLE
Culebra cannot click on ImageButton.

### ISSUE THREAD

**Issue by homandiy** [dtmilano/AndroidViewClient#290]
I use ImageButton on my MediaPlayer. But the Culebra cannot click on ImageButton.

**Comment by dtmilano** [comment]
Can you please specify how are you clicking on the ImageButton?

**Comment by homandiy** [comment]
I tried to play MediaPlayer with ImageButton. Which player is from
GStreamer:
https://gstreamer.freedesktop.org/documentation/tutorials/android/media-player.html?gi-language=c
The Culebra started the app on Emulator, but the Culebra could not click
anything.

**Comment by dtmilano** [comment]
This clicks on an `ImageButton` without issues:

```python
obj_ref = helper.until.find_object(body={"checkable":False,"clazz":"android.widget.ImageButton","clickable":True,"depth":None,"desc":"Navigate up","pkg":"com.android.settings","res":"","scrollable":False,"text":"","index":None,"instance":None})
response = helper.ui_device.wait(oid=obj_ref.oid)
helper.ui_object2.click(oid=response['oid'])
```
