### ISSUE TITLE
Culebra on Android Game

### ISSUE THREAD

**Issue by NaachooT** [dtmilano/AndroidViewClient#291]
I'm trying to get all text labels on a poker app game:

https://i.imgur.com/aoKmKdu.png

The problem is when I use the AndroidViewClient dump I only get this:

`android.widget.FrameLayout
   android.view.View
   android.widget.EditText`

Then my question is if I can get all those text labels or it is impossible because from a game can't be processed by Culebra.

Thanks.

P.S: I can write it in spanish if anything is not clear xD

**Comment by dtmilano** [comment]
They might be custom views or images.

Can you share the full output of `dump --all`.

**Comment by canonsky1992** [comment]
> I'm trying to get all text labels on a poker app game:
> 
> https://i.imgur.com/aoKmKdu.png
> 
> The problem is when I use the AndroidViewClient dump I only get this:
> 
> `android.widget.FrameLayout android.view.View android.widget.EditText`
> 
> Then my question is if I can get all those text labels or it is impossible because from a game can't be processed by Culebra.
> 
> Thanks.
> 
> P.S: I can write it in spanish if anything is not clear xD

Hello NaachooT , 
Do you have CulebraTester and  culebratester instrumentation apk file?

**Comment by WangYanqing** [comment]
> > I'm trying to get all text labels on a poker app game:
> > https://i.imgur.com/aoKmKdu.png
> > The problem is when I use the AndroidViewClient dump I only get this:
> > `android.widget.FrameLayout android.view.View android.widget.EditText`
> > Then my question is if I can get all those text labels or it is impossible because from a game can't be processed by Culebra.
> > Thanks.
> > P.S: I can write it in spanish if anything is not clear xD
> 
> Hello NaachooT ,
> Do you have CulebraTester and culebratester instrumentation apk file?

The link of the 2 apk files cannot be found. And also cannot find the 2 apks from google play's search.

**Comment by dtmilano** [comment]
https://github.com/dtmilano/CulebraTester2-public/actions/runs/815572695 is where you can find the apks to download and install (see Artifacts).

**Comment by NaachooT** [comment]
`<hierarchy rotation="0">
	<node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.kpgame.PokerBros" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]">
		<node index="0" text="" resource-id="" class="android.widget.LinearLayout" package="com.kpgame.PokerBros" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]">
			<node index="0" text="" resource-id="android:id/content" class="android.widget.FrameLayout" package="com.kpgame.PokerBros" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]">
				<node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.kpgame.PokerBros" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]">
					<node index="0" text="" resource-id="" class="android.view.View" package="com.kpgame.PokerBros" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,1920]"/>
					<node NAF="true" index="1" text="" resource-id="" class="android.widget.EditText" package="com.kpgame.PokerBros" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[0,0][1080,136]"/></node>
			</node>
		</node>
	</node>
</hierarchy>`
