### ISSUE TITLE
systex error

### ISSUE THREAD

**Issue by THAVASIGTI** [dtmilano/AndroidViewClient#292]
adbclient.py", line 259

  File "/usr/local/lib/python3.6/dist-packages/com/dtmilano/android/adb/adbclient.py", line 259
    except socket.error, ex:
                       ^
SyntaxError: invalid syntax

**Comment by dtmilano** [comment]
https://github.com/dtmilano/AndroidViewClient/blob/master/src/com/dtmilano/android/adb/adbclient.py#L259

line 259 is just a `print` statement.

Are you on the latest version?
