### ISSUE TITLE
[Errno 8] nodename nor servname provided, or not known.

### ISSUE THREAD

**Issue by vikasg603** [dtmilano/AndroidViewClient#295]
As we know, genymotion provides us with the Genymotion Cloud service through multiple cloud providers.
Currently, I am using https://aws.amazon.com/marketplace/pp/prodview-tsr5r2gq25hd6

I can connect my device with the ADB. Still, while running androidviewclient or dump, I am continually getting an error message "[Errno 8] nodename nor servname provided, or not known."

I also tried adding a serial no, but no luck and getting the same error message.

Is there any way to resolve this?

**Comment by dtmilano** [comment]
Are you using a SSH tunnel?
Can you show some details?

**Comment by vikasg603** [comment]
I tried using both the way.
1) Connecting adb directly
2) Connecting using ssh

I guess androidviewclient is not able to connect with the adb outside localhost, but not even sure why it's not connecting even with ssh.

**Comment by dtmilano** [comment]
I tested creating a tunnel like this

```
ssh -i key.pem -NL 5555:localhost:5555 shell@xxxx.us-west-2.compute.amazonaws.com
```

and then

```
dump
```

worked fine

```
android.widget.FrameLayout  
   android.view.View com.android.launcher3:id/scrim_view 
      android.view.View  
   android.widget.ScrollView com.android.launcher3:id/workspace 
      android.appwidget.AppWidgetHostView com.android.launcher3:id/qsb_widget 
         android.widget.ImageView com.android.quicksearchbox:id/search_icon 
         android.widget.TextView com.android.quicksearchbox:id/search_widget_text 
      android.widget.TextView  Contacts
   android.widget.TextView  Messaging
   android.widget.TextView  Email
   android.widget.TextView  WebView Browser Tester
   android.widget.TextView  Music
   android.widget.TextView  Gallery
   android.widget.TextView  Camera
```

**Comment by vikasg603** [comment]
My bad for the ssh username; I wrote ubuntu rather than the shell.
Sorry for the confusion.
