### ISSUE TITLE
Multi-swipe

### ISSUE THREAD

**Issue by Proficus** [dtmilano/AndroidViewClient#296]
I can't figure out how to do:
Click down - move - move - move... - click up
I really need help, I've been looking for a solution for a week and I don't find anything.
I need to automate a game that has a lot of repetitive swipes to harvest wheat

**Comment by dtmilano** [comment]
Something like this: https://www.youtube.com/watch?v=Ntc2Zp9NGas&t=68s

Take a look at at [AdbClient.drag()](https://github.com/dtmilano/AndroidViewClient/blob/master/src/com/dtmilano/android/adb/adbclient.py#L953)

**Comment by Proficus** [comment]
> Something like this: https://www.youtube.com/watch?v=Ntc2Zp9NGas&t=68s
> 
> Take a look at at [AdbClient.drag()](https://github.com/dtmilano/AndroidViewClient/blob/master/src/com/dtmilano/android/adb/adbclient.py#L953)

Here only 2 points, but i need 10+
I find solution with sendevent
