### ISSUE TITLE
startActivity() doesn't work

### ISSUE THREAD

**Issue by SadLandscape** [dtmilano/AndroidViewClient#297]
device.startActivity("com.narvii.amino.master/com.narvii.account.LoginActivity")
doesn't work just doesn't do anything

**Comment by dtmilano** [comment]
This works as expected for me

```
#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import sys
import os

from com.dtmilano.android.viewclient import ViewClient

device, serialno = ViewClient.connectToDeviceOrExit()

cmp = 'com.android.chrome/com.google.android.apps.chrome.Main'
device.startActivity(cmp)
```

Try it a see what happens, and provide more details, logs, etc. if your error persists.

**Comment by SadLandscape** [comment]
> This works as expected for me
> 
> ```
> #! /usr/bin/env python3
> # -*- coding: utf-8 -*-
> 
> import re
> import sys
> import os
> 
> from com.dtmilano.android.viewclient import ViewClient
> 
> device, serialno = ViewClient.connectToDeviceOrExit()
> 
> cmp = 'com.android.chrome/com.google.android.apps.chrome.Main'
> device.startActivity(cmp)
> ```
> 
> Try it a see what happens, and provide more details, logs, etc. if your error persists.

Yeah I tried that too, it works but the activoty I got from adb shell doesn't work

**Comment by SadLandscape** [comment]
Maybe an app issue :/
