### ISSUE TITLE
How to deal with file dialog

### ISSUE THREAD

**Issue by Benmitn** [dtmilano/AndroidViewClient#298]
Rn im dealing with the problem of completing a file dialoge via AndroidViewClient. 
I am using Bluestack and when trying to import files from the windows pc to the emulator you need to choose the files you want to import. Is there any way to process the file dialog with AndroidViewClient? 

I thought it would be possible with something similar to seleniums option where you send_keys(file_path) to the input. But I have not found any option to send entire text via AndroidViewClient?

**Comment by dtmilano** [comment]
If I understand correctly the dialog is a Windows dialog so you may need to find a tool to do that kind of automation. Similar to what AndroidViewClient/culebra does on the android side.

Perhaps you can post some screenshots and additional details if this is not the case.
