### ISSUE TITLE
please Help me with touch not response

### ISSUE THREAD

**Issue by zhangwenting0224** [dtmilano/AndroidViewClient#301]
Dear author

I seem to have set the environment and options, but strangely, all my actions seem to be unresponsive. Where is the wrong setting? Any help will be greatly appreciated!
![sp220213_175208](https://user-images.githubusercontent.com/71390495/153747817-7e1786e9-3252-475f-bfd1-2f90353d4d72.png)
![sp220213_175339](https://user-images.githubusercontent.com/71390495/153747818-e66100fa-6c0f-43e9-80cc-e228baaa7a59.png)

**Comment by zhangwenting0224** [comment]
I seem to have found the problem
Everything is normal in Huawei cdy-an20
At miui9 5 an error has occurred

![Uploading sp220213_225821.png…]()

**Comment by dtmilano** [comment]
Interesting. I understand that is the same computer, same python, etc. and everything works for **Huawei** but fails for **miui**.

If you can provide some more information, logs and debug info we can possibly determine the problem.

**Comment by zhangwenting0224** [comment]
I finally solved this problem by opening 【allow USB debugging to modify permissions or simulate clicking】in debugging mode
Thank you again!
