### ISSUE TITLE
Example of using Pinch

### ISSUE THREAD

**Issue by gonzalesMK** [dtmilano/AndroidViewClient#323]
Hey folks, would you mind sharing an example on how to use pinch ? 

I tried this piece of code without success:
```python
oid=helper.ui_device.find_object(pkg="my.game.package").oid
helper.ui_object.pinch_in(oid=oid, percentage=10,steps=100)
```

But I got this error: 
``` 
ERROR: java.lang.ClassCastException: androidx.test.uiautomator.UiObject2 cannot be cast to androidx.test.uiautomator.UiObject
`` `

**Comment by dtmilano** [comment]
Try

```
oid=helper.ui_device.find_object(ui_selector="package@my.game.package").oid
helper.ui_object.pinch_in(oid=oid, percentage=10, steps=100)
```

because depending on the selector `find_object` either returns `UiObject` or `UiObject2`.

**Comment by dtmilano** [comment]
Check https://mrin9.github.io/OpenAPI-Viewer/#/load/https%3A%2F%2Fraw.githubusercontent.com%2Fdtmilano%2FCulebraTester2-public%2Fmaster%2Fopenapi.yaml for more details.

**Comment by dtmilano** [comment]
![avc-pinch-out-2](https://github.com/dtmilano/AndroidViewClient/assets/982482/46f2e5cd-485b-4cd9-a9de-041e2cef47f8)

This is an example of pinch out.
