### ISSUE TITLE
`__findViewWithAttributeInTreeThatMatches` should use `search` instead of `match`

### ISSUE THREAD

**Issue by jrafaaael** [dtmilano/AndroidViewClient#330]
I'm trying something like `client.findViewWithAttributeThatMatches(attr="text", regex=re.compile(fr"\babc\b"))`. however, if "abc" isn't at beggining of the text, the view doesn't match

Changing `regex.match` to `regex.search` fix the issue https://github.com/dtmilano/AndroidViewClient/blob/9be41baa795fda4bcbb4b746511bb38ae5cf3d6f/src/com/dtmilano/android/viewclient.py#L3958

It doesn't seem to break anything

**Comment by dtmilano** [comment]
Nice finding. Feel free to create a pull request.

**Comment by dtmilano** [comment]
Take this into account, you can always do it with `match` too:
```
>>> import re
>>> r = re.compile(fr"\babc\b")
>>> r.match("xxx abc yyy")
>>> r = re.compile(fr"^.*\babc\b.*$")
>>> r.match("xxx abc yyy")
<re.Match object; span=(0, 11), match='xxx abc yyy'>
```

**Comment by jrafaaael** [comment]
@dtmilano 
hey! sorry for late response, I was a bit bussy last week

> `^.*\babc\b.*$`

this seems to work like a charm! however, word boundary `/b` only should too
let me PR and discuss further there!
