### ISSUE TITLE
androidviewclient problem with the setting.

### ISSUE THREAD

**Issue by donenx** [dtmilano/AndroidViewClient#77]
Hi I want use androidviewclient. What can i do? This is my problem:
C:\Users\Donato Pastore>cd\

C:>cd AndroidViewClient

C:\AndroidViewClient>java -jar androidviewclient-2.3.24.jar dump
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
] Script terminated due to an exception
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]Traceback (most recent call last):
  File "C:\Users\Donato Pastore\dump", line 138, in <module>
    vc = ViewClient(_ViewClient.connectToDeviceOrExit(__kwargs1), *_kwargs2)
  File "C:\AndroidViewClient\src\com\dtmilano\android\viewclient.py", line 1390,
 in connectToDeviceOrExit
    ViewClient.setAlarm(timeout+5)
  File "C:\AndroidViewClient\src\com\dtmilano\android\viewclient.py", line 1350,
 in setAlarm
    signal.alarm(timeout)
  File "C:\adt-bundle-windows-x86_64-20131030\sdk\tools\lib\jython-standalone-2.
5.3.jar\Lib\signal.py", line 222, in alarm
NotImplementedError: alarm not implemented on this platform

140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyException.doRaise(PyException.java:219)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.Py.makeException(Py.java:1239)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.Py.makeException(Py.java:1243)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.Py.makeException(Py.java:1247)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at signal$py.alarm$14(C:\adt-bundle-windows-x86_64-20131030\sdk\tools\li
b\jython-standalone-2.5.3.jar\Lib\signal.py:239)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at signal$py.call_function(C:\adt-bundle-windows-x86_64-20131030\sdk\too
ls\lib\jython-standalone-2.5.3.jar\Lib\signal.py)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.**call**(PyFunction.java:317)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.viewclient$py.setAlarm$70(C:\AndroidViewClient\s
rc\com\dtmilano\android\viewclient.py:1350)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.viewclient$py.call_function(C:\AndroidViewClient
\src\com\dtmilano\android\viewclient.py)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.**call**(PyFunction.java:317)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.viewclient$py.connectToDeviceOrExit$71(C:\Androi
dViewClient\src\com\dtmilano\android\viewclient.py:1418)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.dtmilano.android.viewclient$py.call_function(C:\AndroidViewClient
\src\com\dtmilano\android\viewclient.py)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.function___call__(PyFunction.java:376)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.**call**(PyFunction.java:371)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyFunction.**call**(PyFunction.java:366)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyObject._callextra(PyObject.java:527)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.pycode._pyx0.f$0(C:\Users\Donato Pastore\dump:140)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.pycode._pyx0.call_function(C:\Users\Donato Pastore\dump)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyTableCode.call(PyTableCode.java:165)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.PyCode.call(PyCode.java:18)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.Py.runCode(Py.java:1275)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.core.__builtin__.execfile_flags(**builtin**.java:522)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225
)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.android.monkeyrunner.ScriptRunner.run(ScriptRunner.java:116)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.android.monkeyrunner.MonkeyRunnerStarter.run(MonkeyRunnerStarter.
java:77)
140415 15:33:19.664:S [MainThread] [com.android.monkeyrunner.MonkeyRunnerOptions
]       at com.android.monkeyrunner.MonkeyRunnerStarter.main(MonkeyRunnerStarter
.java:189)

C:\AndroidViewClient>

**Comment by yourng2794** [comment]
logo@logo:~/CTS/AndroidViewClient-master$ ./Deviceadmin.py
Traceback (most recent call last):
  File "./Deviceadmin.py", line 43, in <module>
    vc = ViewClient(device=device, serialno=serialno)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-10.5.1-py2.7.egg/com/dtmilano/android/viewclient.py", line 2324, in __init__
    self.serialno = self.__mapSerialNo(serialno)
  File "/usr/local/lib/python2.7/dist-packages/androidviewclient-10.5.1-py2.7.egg/com/dtmilano/android/viewclient.py", line 2466, in __mapSerialNo
    raise ValueError("Regular expression not supported as serialno in ViewClient. Found '%s'" % serialno)
ValueError: Regular expression not supported as serialno in ViewClient. Found 'adb server is out of date.  killing...
* daemon started successfully *
unknown'

**Comment by dtmilano** [comment]
If your intention is to use regular expressions for the serial numbers you should use `ViewClient.connectToDeviceOrExit()` as `culebra` generated scripts do:

```python
...
kwargs1 = {'ignoreversioncheck': False, 'verbose': False, 'ignoresecuredevice': False}
device, serialno = ViewClient.connectToDeviceOrExit(**kwargs1)
kwargs2 = {'compresseddump': True, 'startviewserver': True, 'forceviewserveruse': False, 'autodump': False, 'ignoreuiautomatorkilled': True}
vc = ViewClient(device, serialno, **kwargs2)
...
```

in this case the serial number, which can be a regular expression is taken from the script command line

```
example.py 0.*
```
will attempt to connect to a device with serial number starting with `0`.


If you don't want this, you can always specify the serialno in your call as in

```
device, serialno = ViewClient.connectToDeviceOrExit(serialno='0.*', **kwargs1)
```

**Comment by dtmilano** [comment]
Also, please create new issues or StackOverflow questions at http://stackoverflow.com/questions/tagged/androidviewclient, not just add unrelated comments to closed issues.
